import TermConditionsLocalization from 'react-native-localization';

let strings = new TermConditionsLocalization({
 "en-US":{
   termAndConditions:"Terms and Conditions",
   paragraph1:"The purpose of this community is to connect people sharing mutual interest in animals and possibly find suitable mates for their pets. As such, Paranu may never be held responsible for whatever members do or any outcome of people interacting on its platform results in. It is your own responsibility to comply with the laws and regulations in your country. By using this service and thereby agreeing to these terms you agree to not to file any law suite against Paranu.",
   paragraph2Line1:"In order to become a member and use this service, you must be 16 years of age or have consent from your legal guardian.",
   paragraph2Line2:"Everything published and written on Paranu may not be deliberately incorrect or infringing. Obscene or in some way sexually inappropriate material such as images or text will not be accepted.",
   paragraph2Line3:"You who choose to accept and comply with the following terms and conditions as a member must confirm by agreeing to these terms.",
   paragraph2Line4:"We do not allow members to advertise other companies and their products or services.",
   paragraph2Line5:"Paranu can not guarantee or assure that content published in this service is correct.",
   paragraph2Line6:"We reserve the right to terminate memberships at any time without reimbursement of membership costs if these terms are not complied with.",
   paragraph2Line7:"Privacy notice: Content published in this service will never be sold by Paranu or otherwise distributed to third parties without your consent.",
   paragraph2Line8:"All material, including the Paranu trademark, is protected by copyright law.",

 },
 en:{
  termAndConditions:"Terms and Conditions",
  paragraph1:"The purpose of this community is to connect people who share a mutual interest in animals, possibly looking for a suitable mate for his/her pet, or to help people in need of animal sitting. As such type of community, Paranu AB shall never be held responsible for whatever material members publish on the platform (Paranu).",
  paragraph2Line1:"In order to become a member and use this service, you must be 16 years of age or have consent from your legal guardian.",
  paragraph2Line2:"Everything published and written on Paranu may not be deliberately incorrect or infringing. Obscene or in some way sexually inappropriate material such as images or text will not be accepted.",
  paragraph2Line3:"You who choose to accept and comply with the following terms and conditions as a member must confirm by agreeing to these terms.",
  paragraph2Line4:"We do not allow members to advertise other companies and their products or services.",
  paragraph2Line5:"Paranu can not guarantee or assure that content published in this service is correct.",
  paragraph2Line6:"We reserve the right to terminate memberships at any time without reimbursement of membership costs if these terms are not complied with.",
  paragraph2Line7:"Privacy notice: Content published in this service will never be sold by Paranu or otherwise distributed to third parties without your consent.",
  paragraph2Line8:"All material, including the Paranu trademark, is protected by copyright law.",
 },
 it: {
  termAndConditions:"Termini e condizioni",
  paragraph1:"Lo scopo di questa comunità è quello di fare connocenza con le persone che condividono l'interesse reciproco per gli animali e possibilmente trovare compagni adatti per i loro animali domestici. In quanto tale, Paranu potrebbe non essere mai detenutoresponsabile per qualsiasi membro o risultato di persone che interagiscono con esso risultati della piattaforma. È responsabilità dell'utente rispettare le leggi e regolamenti nel vostro paese. Utilizzando questo servizio e quindi accettando questi termini, accetti di non presentare alcuna richiesta di legge contro Paranu.",
  paragraph2Line1:"Per diventare un membro e utilizzare questo servizio, devi essere 16 anni o hai il consenso del tuo tutore legale.",
  paragraph2Line2:"Tutto pubblicato e scritto su Paranu potrebbe non essere deliberatamente scorrettoo in violazione. Osceno o in qualche modo sessualmente inappropriato materiale come immagini o testo non saranno accettati.",
  paragraph2Line3:"L'utente che sceglie di accettare e rispettare i seguenti termini e condizioni di un membro deve confermare accettando questi termini.",
  paragraph2Line4:"Non consentiamo ai membri di pubblicizzare altre società e i loro prodotti o servizi.",
  paragraph2Line5:"Paranu non può garantire o assicurare che il contenuto pubblicato in questo servizio sia corretto.",
  paragraph2Line6:"Ci riserviamo il diritto di annulare l'iscrizione in qualsiasi momento senza rimborso dei costi di adesione se questi termini non sono rispettati.",
  paragraph2Line7:"Informativa sulla privacy: I contenuti pubblicati in questo servizio non saranno mai venduti da Paranu o altrimenti distribuiti a terzi senza il vostro consenso.",
  paragraph2Line8:"Tutto il materiale, incluso il marchio Paranu, è protetto dalla legge sul copyright.",
 },
 fr:{
  termAndConditions:"Termes et conditions",
  paragraph1:"Le but de cette communauté est de mettre en contact des personnes partageant un intérêt mutuel pour les animaux, en recherchant éventuellement un compagnon approprié pour son animal de compagnie, ou d’aider les personnes ayant besoin de s’asseoir. En tant que tel type de communauté, Paranu AB ne pourra en aucun cas être tenu responsable du matériel publié par ses membres sur la plateforme (Paranu).",
  paragraph2Line1:"Pour devenir membre et utiliser ce service, vous devez avoir 16 ans ou avoir le consentement de votre tuteur légal.",
  paragraph2Line2:"Tout ce qui est publié et écrit sur Paranu ne peut être délibérément incorporé ou enfreint. Des éléments obscènes ou sexuellement inappropriés tels que des images ou du texte ne seront pas acceptés.",
  paragraph2Line3:"Vous choisissez d'accepter et de vous conformer aux termes et conditions suivants en tant que membre en acceptant ces termes.",
  paragraph2Line4:"Nous n'autorisons pas les membres à annoncer d'autres sociétés et leurs produits ou services.",
  paragraph2Line5:"Paranu ne peut garantir ni assurer que le contenu publié dans ce service soit correct.",
  paragraph2Line6:"Nous nous réservons le droit de mettre fin à l'adhésion à tout moment sans remboursement des frais d'adhésion si ces conditions ne sont pas respectées.",
  paragraph2Line7:"Remarque sur la confidentialité: le contenu publié dans ce service ne sera jamais vendu par Paranu ni autrement distribué à des tiers sans votre consentement.",
  paragraph2Line8:"Tout le matériel, y compris la marque Paranu, est protégé par les droits d'auteur.",
 },
 es:{
  termAndConditions:"Términos y Condiciones",
  paragraph1:"El propósito de esta comunidad es conectar a las personas que comparten intereses mutuos en los animales y posiblemente encontrar parejas adecuadas para sus mascotas. Como tal, Paranu nunca será responsable de lo que hagan los miembros o el resultado de las personas que interactúan en su plataforma. Es su responsabilidad cumplir con las leyes y regulaciones de su país. Al utilizar este servicio y aceptar estos términos, acepta no presentar ningúna demanda legal contra Paranu.",
  paragraph2Line1:"Para ser miembro y utilizar este servicio, debe tener 16 años de edad o tener el consentimiento de su tutor legal.",
  paragraph2Line2:"Todo lo publicado y escrito en Paranu no puede ser deliberadamente incorrecto o ofensivo. Materiales como imágenes o texto obsceno o de alguna manera sexualmente inapropiadonNo se aceptará .",
  paragraph2Line3:"Usted que elige aceptar y cumplir con los siguientes términos y condiciones como miembro debe confirmar al aceptar estos términos.",
  paragraph2Line4:"No permitimos que los miembros anuncien a otras compañías y sus productos o servicios.",
  paragraph2Line5:"Paranu no puede garantizar ni asegurar que el contenido publicado en este servicio es correcto.",
  paragraph2Line6:"Nos reservamos el derecho de cancelar la membresía en cualquier momento sin reembolso de los costos de la membresía si estos términos no se cumplen.",
  paragraph2Line7:"Aviso de privacidad: Paranu nunca venderá el contenido publicado en este servicio ni lo distribuirá a terceros sin su consentimiento.",
  paragraph2Line8:"Todo el material, incluida la marca registrada Paranu, está protegido por la ley de derechos de autor.",
 },
 sv:{
  termAndConditions:"Villkor",
  paragraph1:"Syftet med denna gemenskap är att sammanföra människor som delar det gemensamma intresset djur och eventuellt vill hitta lämpliga partners för sina djur. Som sådan ska Paranu aldrig hållas ansvarig för vad medlemmar gör eller vad resultatet av medlemmar som interagerat på denna plattform blir. Det är ditt ansvar att följa lagar och regler i det land där du befinner dig. Genom att använda vår tjänst och därigenom godkänna dessa villkor accepterar du att du inte kan stämma Paranu.",
  paragraph2Line1:"För att bli medlem och använda denna tjänst måste du vara 16 år eller ha godkännande av din målsman. ",
  paragraph2Line2:"Inget som publiceras och skrivs på Paranu får medvetet vara felaktigt eller kränkande. Oanständigt eller på något sätt sexuellt olämpligt material som bilder eller text accepteras inte.",
  paragraph2Line3:"Du som väljer att acceptera och följa dessa villkor som medlem måste bekräfta genom att godkänna villkoren.",
  paragraph2Line4:"Vi tillåter inte att medlemmar annonserar för andra företag och deras produkter eller tjänster.",
  paragraph2Line5:"Paranu kan inte garantera eller försäkra att innehåll som publiceras i den här tjänsten är korrekt.",
  paragraph2Line6:"Vi förbehåller oss rätten att säga upp medlemskap när som helst utan ersättning av medlemsavgifter om dessa villkor inte följs.",
  paragraph2Line7:"Sekretessmeddelande: Innehåll som publiceras i denna tjänst kommer aldrig att säljas av Paranu eller på annat sätt distribueras till tredje part utan ditt samtycke.",
  paragraph2Line8:"Allt material, inklusive varumärket Paranu, är skyddat av upphovsrätten.",
 },
 ddr:{
  termAndConditions:"Geschäftsbedingungen",
  paragraph1:"Der Zweck dieser Gemeinschaft ist es, Menschen miteinander zu verbinden, die ein gemeinsames Interesse an Tieren haben und möglicherweise passende Partner für ihre Haustiere finden. Paranu darf daher niemals abgehalten werden verantwortlich für das, was die Mitglieder tun oder für das Ergebnis der Interaktion mit den Mitgliedern Plattform führt in. Es liegt in Ihrer eigenen Verantwortung, die Gesetze und Gesetze einzuhalten Vorschriften in Ihrem Land. Durch die Nutzung dieses Dienstes und die Zustimmung zu diesen Bedingungen stimmen Sie zu, keine Klage gegen Paranu einzureichen.",
  paragraph2Line1:"Um Mitglied zu werden und diesen Service zu nutzen, müssen Sie 16 Jahre alt sein oder von Ihrem gesetzlichen Vormund eingewilligt werden.",
  paragraph2Line2:"Alles, was auf Paranu veröffentlicht und geschrieben wird, ist möglicherweise nicht absichtlich falsch oder verletzend. Obszön oder sexuell unangemessen Material wie Bilder oder Text wird nicht akzeptiert.",
  paragraph2Line3:"Sie, die sich dafür entscheiden, die folgenden Bedingungen als Mitglied zu akzeptieren und zu befolgen, müssen dies durch die Zustimmung zu diesen Bedingungen bestätigen.",
  paragraph2Line4:"Wir erlauben Mitgliedern nicht, für andere Unternehmen und deren Produkte oder Dienstleistungen zu werben.",
  paragraph2Line5:"Paranu kann nicht garantieren oder versicheren, dass der in diesem Service veröffentlichte Inhalt korrekt ist.",
  paragraph2Line6:"Wir behalten uns das Recht vor, Mitgliedschaften jederzeit ohne Erstattung zu kündigen von Mitgliedschaftskosten, wenn diese Bedingungen nicht eingehalten werden.",
  paragraph2Line7:"Datenschutzerklärung: Inhalte, die in diesem Service veröffentlicht werden, werden niemals von Paranu verkauft oder anderweitig ohne Ihre Zustimmung an Dritte weitergegeben.",
  paragraph2Line8:"Das gesamte Material einschließlich der Marke Paranu ist urheberrechtlich geschützt.",
 },
 ru:{
  termAndConditions:"Условия и положения",
  paragraph1:"Цель этого сообщества - объединить людей разделяющих взаимный интерес к животным, и возможно найти подходящую пару для своих питомцев. Таким образом, Paranu не несёт ответственности за то, что участники делают или за результат взаимодействия людей на этой платформе. Вы несёте ответственность за соблюдение законов и правил в вашей стране. Используя нашу услугу вы тем самым соглашаетесь с этими условиями и не можете подавать никаких исков против Paranu.",
  paragraph2Line1:"Чтобы стать участником и воспользоваться этой услугой, вам должно быть 16 лет или получить согласие от вашего законного опекуна.",
  paragraph2Line2:"Всё что опубликовывается и пишется на Paranu не может быть неверным или нарушающим права. Непристойный или в некотором роде сексуально неуместный материал, такие как изображения или текст, не принимаются.",
  paragraph2Line3:"Вы, которые решили принять и соблюдать следующие условия в качестве участника, должны подтвердить свое согласие с этими условиями.",
  paragraph2Line4:"Мы не разрешаем участникам рекламировать другие компании и их продукты или услуги.",
  paragraph2Line5:"Paranu не может гарантировать что содержание опубликованного на этой платформе является правильным.",
  paragraph2Line6:"Мы оставляем за собой право прекратить членство в любое время без возмещения членских взносов если эти условия не соблюдаются.",
  paragraph2Line7:"Уведомление о конфиденциальности: Содержание опубликованного на этой платформе никогда не будет продано Paranu или иным образом передано третьим лицам без вашего согласия.",
  paragraph2Line8:"Все материалы, включая товарный знак Paranu защищены законом об авторском праве.",
 }
});
export default strings