import LoginTypeLocalization from 'react-native-localization';

let strings = new LoginTypeLocalization({
 "en-US":{
  internetIssue: "Internet issue",
   login:"LOGIN",
   noLocation:"no location",
   register:"REGISTER",
   pleaseWait:"Please Wait",
   paranulocation: "Paranu need location to match the nearest available pets",
   cancel: "Cancel",
   setting: "Setting",
   permission: "Permissions",
 },
 en:{
  internetIssue: "Internet Issue",
   login:"LOGIN",
   noLocation:"no location",
   register:"REGISTER",
   pleaseWait:"Please Wait",
   paranulocation: "Paranu need location to match the nearest available pets",
   cancel: "Cancel",
   setting: "Setting",
   permission: "Permissions",
 },
 it: {
  internetIssue: "Problema Internet",
  login:"ACCESSO",
  noLocation:"Nessuna posizione",
  register:"REGISTRARE",
  pleaseWait:"Prego aspettate",
  paranulocation: "Paranu ha bisogno di posizione per abbinare gli animali domestici più vicini disponibili",
  cancel: "Annulla",
   setting: "Ambientazione",
   permission: "permessi",
 },
 fr:{
  internetIssue: "Problème Internet",
  login:"S'IDENTIFIER",
  noLocation:"pas d'emplacement",
  register:"S'ENREGISTRER",
  pleaseWait:"Patientez, s'il vous plaît",
  paranulocation: "Paranu besoin d'un emplacement pour correspondre aux animaux disponibles les plus proches",
  cancel: "Annuler",
   setting: "Réglage",
   permission: "Les permissions",
},
es:{
  internetIssue: "Problema de internet",
  login:"INICIAR SESIÓN",
  noLocation:"Sin ubicacion",
  register:"REGISTRAR",
  pleaseWait:"Por favor espera",
  paranulocation: "Paranu necesita ubicación para coincidir con las mascotas disponibles más cercanas",
  cancel: "Cancelar",
   setting: "Ajuste",
   permission: "Permisos",
},
sv:{
  internetIssue: "Nätverksproblem",
  login:"LOGGA IN",
  noLocation:"Ingen plats",
  register:"REGISTRERA",
  pleaseWait:"Vänligen Letar",
  paranulocation: "Paranu behöver plats för att matcha närmaste tillgängliga husdjur",
  cancel: "Annullera",
   setting: "Miljö",
   permission: "Behörigheter",
},
ddr:{
  internetIssue: "Internet-Problem",
  login:"Anmeldung",
  noLocation:"Kein Platz",
  register:"REGISTRIEREN",
  pleaseWait:"Warten Sie mal bitte",
  paranulocation: "Paranu benötigt einen Standort, um den nächstgelegenen Haustieren zu entsprechen",
  cancel: "Stornieren",
   setting: "Rahmen",
   permission: "Berechtigungen",
},
ru:{
  internetIssue: "Проблемы с сетью",
  login:"ЗАЙТИ",
  noLocation:"Нет места",
  register:"РЕГИСТРИРОВАТСЯ",
  pleaseWait:"Пожалуйста подождите",
  paranulocation: "Парану нужно местоположение, чтобы соответствовать ближайшим домашним животным",
  cancel: "отменить",
   setting: "настройка",
   permission: "права доступа",
}

});
export default strings