import PetULookingForLocalization from 'react-native-localization';

let strings = new PetULookingForLocalization({
 "en-US":{
   alert1:"Something is missing",
   whatAreYouLookingFor:"What Are You Looking For?",
   petCategory:"Pet Category",
   type:"Type",
   size:"Size",
   sex:"Sex",
   next:"Next",
   selectcategoryofpet: "Select category of pet",
   selecttypeofpet: "Select type of pet",
   selectsizeofpet: "Select size of the pet",
   selectsexofpet: "Select sex of the pet",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",

 },
 en:{
  alert1:"Something is missing",
  whatAreYouLookingFor:"What Are You Looking For?",
  petCategory:"Pet Category",
  type:"Type",
  size:"Size",
  sex:"Sex",
  next:"Next",
  selectcategoryofpet: "Select category of pet",
   selecttypeofpet: "Select type of pet",
   selectsizeofpet: "Select size of the pet",
   selectsexofpet: "Select sex of the pet",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
 },
 it: {
  alert1:"Manca qualcosa",
  whatAreYouLookingFor:"Che cosa sta cercando?",
  petCategory:"Categoria dell'animale domestico",
  type:"genere",
  size:"Taglia",
  sex:"Sesso",
  next:"Il prossimo",
  selectcategoryofpet: "Seleziona la categoria di animale domestico",
   selecttypeofpet: "Seleziona il tipo di animale domestico",
   selectsizeofpet: "Seleziona la taglia dell'animale",
   selectsexofpet: "Seleziona il sesso dell'animale",
   bird: "Uccello",
    cat: "Gatto",
    cattle: "Bestiame",
    dog: "Cane",
    fish: "Pesce",
    horse: "Cavallo",
    miniPig: "Mini maiale",
    rabbit: "coniglio",
    rodent: "Roditore",
    reptile: "Rettile",
    other: "Altro",
    crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
    small: "Piccolo",
    medium: "medio",
    big: "Grande",
    dosntMetter: "Non importa",
    male: "Maschio",
    female: "Femmina",
 },
 fr:{
  alert1:"Un champ est manquant",
  whatAreYouLookingFor:"Que cherchez-vous?",
  petCategory:"Catégorie de compagnie",
  type:"Type",
  size:"Taille",
  sex:"Sexe",
  next:"Suivant",
  selectcategoryofpet: "Sélectionnez une catégorie d'animal",
   selecttypeofpet: "Sélectionnez le type d'animal de compagnie",
   selectsizeofpet: "Sélectionnez la taille de l'animal",
   selectsexofpet: "Sélectionnez le sexe de l'animal",
   bird: "Oiseau",
    cat: "Chat",
    cattle: "Bétail",
    dog: "Chien",
    fish: "Poisson",
    horse: "Cheval",
    miniPig: "Miniporc",
    rabbit: "lapin",
    rodent: "Rongeur",
    reptile: "Reptile",
    other: "Autre",
    crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
    small: "Petit",
    medium: "Moyen",
    big: "Grand",
    dosntMetter: "N'a pas d'importance",
    male: "Mâle",
    female: "Femelle",
 },
 es:{
  alert1:"Algo falta",
  whatAreYouLookingFor:"¿Qué estás buscando?",
  petCategory:"Categoría de mascota",
  type:"Tipo",
  size:"tamaño",
  sex:"Sexo",
  next:"Siguiente",
  selectcategoryofpet: "Seleccione categoría de mascota",
   selecttypeofpet: "Seleccione el tipo de mascota",
   selectsizeofpet: "Selecciona el tamaño de la mascota.",
   selectsexofpet: "Selecciona el sexo de la mascota.",
   bird: "Pájaro",
    cat: "Gato",
    cattle: "Ganado",
    dog: "Perro",
    fish: "Pez",
    horse: "Caballo",
    miniPig: "Mini cerdo",
    rabbit: "Conejo",
    rodent: "Roedor",
    reptile: "Reptil",
    other: "Otro",
    crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
    small: "Pequeña",
    medium: "Medio",
    big: "Grande",
    dosntMetter: "No importa",
    male: "Masculino",
    female: "Hembra",
 },
 sv:{
  alert1:"Något saknas",
  whatAreYouLookingFor:"Vad letar du efter?",
  petCategory:"Husdjurskategori",
  type:"Typ",
  size:"Storlek",
  sex:"Kön",
  next:"Nästa",
  selectcategoryofpet: "Välj kategori av husdjur",
   selecttypeofpet: "Välj typ av husdjur",
   selectsizeofpet: "Välj storlek på husdjuret",
   selectsexofpet: "Välj husdjurets kön",
   bird: "Fågel",
    cat: "Katt",
    cattle: "Boskap",
    dog: "Hund",
    fish: "Fisk",
    horse: "Häst",
    miniPig: "Minigris",
    rabbit: "Kanin",
    rodent: "Gnagare",
    reptile: "Reptil",
    other: "Andra",
    crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
    small: "Liten",
    medium: "Mellan",
    big: "Stor",
    dosntMetter: "Spelar ingen roll",
    male: "Hane",
    female: "Hona",
 },
 ddr:{
  alert1:"Etwas fehlt",
  whatAreYouLookingFor:"Wonach suchen Sie?",
  petCategory:"Haustierkategorie",
  type:"Art",
  size:"Größe",
  sex:"Sex",
  next:"Nächste",
  selectcategoryofpet: "Wählen Sie die Kategorie des Haustiers aus",
   selecttypeofpet: "Wählen Sie den Haustiertyp",
   selectsizeofpet: "Wählen Sie die Größe des Haustieres",
   selectsexofpet: "Wählen Sie das Geschlecht des Haustieres aus",
   bird: "Vogel",
    cat: "Katze",
    cattle: "Das Vieh",
    dog: "Hund",
    fish: "Fisch",
    horse: "Pferd",
    miniPig: "Mini Schwein",
    rabbit: "Hase",
    rodent: "Nagetier",
    reptile: "Reptil",
    other: "Andere",
    crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
    small: "Klein",
    medium: "Mittel",
    big: "Groß",
    dosntMetter: "speillt keine Rolle",
    male: "Männlich",
    female: "Weiblich",
 },
 ru:{
  alert1:"Чего то не хватает",
  whatAreYouLookingFor:"Что Вы ищете?",
  petCategory:"Категория домашних животных",
  type:"Тип",
  size:"Размер",
  sex:"Пол",
  next:"следующий",
  selectcategoryofpet: "Выберите категорию питомца",
   selecttypeofpet: "Выберите тип питомца",
   selectsizeofpet: "Выберите размер домашнего животного",
   selectsexofpet: "Выберите пол питомца",
   bird: "Птица",
    cat: "Кошка/Кот",
    cattle: "крупный рогатый скот",
    dog: "Собака",
    fish: "Рыба",
    horse: "Лошадь",
    miniPig: "Мини свинья",
    rabbit: "Кролик",
    rodent: "Грызун",
    reptile: "Рептилия",
    other: "Другие",
    crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
    small: "Маленький",
    medium: "Средний",
    big: "Большой",
    dosntMetter: "Не имеет значения",
    male: "Он",
    female: "Она",
 }
});
export default strings