const SET_USER = 'SET_USER';
const ALTER_USER = 'ALTER_USER';
const ALTER_JUST_USER='ALTER_JUST_USER';
const SET_YOUR_PET='SET_YOUR_PET';
const SET_INDEX_OF_PET='SET_INDEX_OF_PET';
const SET_ALL_MESSAGE='SET_ALL_MESSAGE';
const GET_ALL_PETS='GET_ALL_PETS';
const GET_ALL_ADS='GET_ALL_ADS';
const GET_ALL_MATCH_LIST='GET_ALL_MATCH_LIST';
const SET_BOTTOM_TAB_BAR="SET_BOTTOM_TAB_BAR";
const SET_BOTTOM_TAB_BAR_INDEX="SET_BOTTOM_TAB_BAR_INDEX"
const SET_TOKEN="SET_TOKEN"
const SET_LANGUAGE="SET_LANGUAGE"
const SET_LOCATION="SET_LOCATION"
const DISTANCE_CHANGED="DISTANCE_CHANGED"

export {
    SET_USER,
    ALTER_USER,
    ALTER_JUST_USER,
    SET_INDEX_OF_PET,
    SET_YOUR_PET,
    SET_ALL_MESSAGE,
    GET_ALL_PETS,
    GET_ALL_ADS,
    GET_ALL_MATCH_LIST,
    SET_BOTTOM_TAB_BAR,
    SET_BOTTOM_TAB_BAR_INDEX,
    SET_TOKEN,
    SET_LANGUAGE,
    SET_LOCATION,
    DISTANCE_CHANGED
};
