import EditProfileLocalization from 'react-native-localization';

let strings = new EditProfileLocalization({
"en-US": {
  alert1: "Please check your internet",
  internetIssue: "Internet issue",
  interest: "Interest",
  pet: "pet",
  deleteImage: "Delete the image",
  delete: "Delete",
  cancel: "Cancel",
  youNeedToHAveAtLeastOneImage: "You need to have at least one image",
  profile: "Profile",
  save: "Save",
  petImages: "Pet Images",
  petCertificates: "Pet Certificates",
  petVideo:"Pet Video",
  petName: "Pet Name",
  petType: "Pet Type",
  age: "Age",
  birthDate: "Birth Date",
  DatePlace: "YYYY-MM-DD",
  breed: "Breed",
  size: "Size",
  sex: "Sex",
  city: "City",
  BeriefInfo: "Brief information",
  lookingFor: "Looking for",
  changeInterest: "Change interest",
  addInterest: "Add interest",
  bird: "Bird",
  cat: "Cat",
  cattle: "Cattle",
  dog: "Dog",
  fish: "Fish",
  horse: "Horse",
  miniPig: "Mini pig",
  rabbit: "Rabbit",
  rodent: "Rodent",
  reptile: "Reptile",
  other: "Other",
  crossBreed: "Crossbreed",
  pureBreed: "Purebred",
  dontKnow: "Don't Know",
  small: "Small",
  medium: "Medium",
  big: "Big",
  dosntMetter: "Doesn't matter",
  male: "Male",
  female: "Female",
  profile: "Profile",
  save: "Save",
  doyouwanttosaveit: "Do you want to save it?",
  ok: "OK",
  months: "Months",
  years: "Years",
  videoAlertTitle:"Sorry",
  videoAlerttxt:"Video duration must be less than 7 seconds",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
en: {
  alert1: "Please check your internet",
  internetIssue: "Internet issue",
  interest: "Interest",
  pet: "pet",
  deleteImage: "Delete the image",
  delete: "Delete",
  cancel: "Cancel",
  youNeedToHAveAtLeastOneImage: "You need to have at least one image",
  profile: "Profile",
  save: "Save",
  petImages: "Pet Images",
  petCertificates: "Pet Certificates",
  petVideo:"Pet Video",
  petName: "Pet Name",
  petType: "Pet Type",
  age: "Age",
  birthDate: "Birth Date",
  DatePlace: "YYYY-MM-DD",
  breed: "Breed",
  size: "Size",
  sex: "Sex",
  city: "City",
  BeriefInfo: "Brief information",
  lookingFor: "Looking for",
  changeInterest: "Change interest",
  addInterest: "Add interest",
  bird: "Bird",
  cat: "Cat",
  cattle: "Cattle",
  dog: "Dog",
  fish: "Fish",
  horse: "Horse",
  miniPig: "Mini pig",
  rabbit: "Rabbit",
  rodent: "Rodent",
  reptile: "Reptile",
  other: "Other",
  crossBreed: "Crossbreed",
  pureBreed: "Purebred",
  dontKnow: "Don't Know",
  small: "Small",
  medium: "Medium",
  big: "Big",
  dosntMetter: "Doesn't matter",
  male: "Male",
  female: "Female",
  profile: "Profile",
  save: "Save",
  doyouwanttosaveit: "Do you want to save it?",
  ok: "OK",
  months: "months",
  years: "Years",
  videoAlertTitle:"Sorry",
  videoAlerttxt:"Video duration must be less than 7 seconds",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
it: {
  alert1: "Per favore controlla il tuo internet",
  internetIssue: "Problema di Internet",
  interest: "interesse",
  pet: "animale domestico",
  deleteImage: "Annullate l'immagine",
  delete: "Annullate",
  cancel: "Annullate",
  youNeedToHAveAtLeastOneImage: "Devi avere almeno un'immagine",
  profile: "Profilo",
  save: "Salvare",
  petImages: "Immagini dell'animale domestico",
  petCertificates: "Certificati per animali domestici",
  petVideo:"Video dell'animale domestico",
  petName: "Nome del cucciolo",
  petType: "Tipo di animale domestico",
  age: "Età",
  birthDate: "Data di nascita",
  DatePlace: "AAAA-MM-DD",
  breed: "Razza",
  size: "Taglia",
  sex: "Sesso",
  city: "Città",
  BeriefInfo: "Breve informazione",
  lookingFor: "Cercando",
  changeInterest: "Cambia interesse",
  addInterest: "Aggiungi interesse",
  bird: "Uccello",
  cat: "Gatto",
  cattle: "Bestiame",
  dog: "Cane",
  fish: "Pesce",
  horse: "Cavallo",
  miniPig: "Mini maiale",
  rabbit: "coniglio",
  rodent: "Roditore",
  reptile: "Rettile",
  other: "Altro",
  crossBreed: "Incrocio",
  pureBreed: "Di razza",
  dontKnow: "Non so",
  small: "Piccolo",
  medium: "medio",
  big: "Grande",
  dosntMetter: "Non importa",
  male: "Maschio",
  female: "Femmina",
  profile: "Profilo",
  save: "Salvare",
  doyouwanttosaveit: "Vuoi salvarlo?",
  ok: "ok",
  months: "Mesi",
  years: "Anni",
  videoAlertTitle:"Scusa",
  videoAlerttxt:"La durata del video deve essere inferiore a 7 secondi",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
fr: {
  alert1: "Prière de vérifier votre connexion internet",
  internetIssue: "Problème Internet",
  interest: "intérêt",
  pet: "Animal de compagnie",
  deleteImage: "Supprimer l'image",
  delete: "Supprimer",
  cancel: "Annuler",
  youNeedToHAveAtLeastOneImage: "Vous devez avoir au moins une image",
  profile: "Profil",
  save: "Sauvegarder",
  petImages: "Images d'animaux",
  petCertificates: "Certificats Animaux",
  petVideo:"Vidéo pour animaux de compagnie",
  petName: "Nom d'animal domestique",
  petType: "Type d'animal",
  age: "Âge",
  birthDate: "Date de naissance",
  DatePlace: "AAAA-MM-JJ",
  breed: "Race",
  size: "Taille",
  sex: "Sexe",
  city: "Ville",
  BeriefInfo: "Information brève",
  lookingFor: "À la recherche de",
  changeInterest: "Changer d'intérêt",
  addInterest: "Ajouter un intérêt",
  bird: "Oiseau",
  cat: "Chat",
  cattle: "Bétail",
  dog: "Chien",
  fish: "Poisson",
  horse: "Cheval",
  miniPig: "Miniporc",
  rabbit: "lapin",
  rodent: "Rongeur",
  reptile: "Reptile",
  other: "Autre",
  crossBreed: "Race croisée",
  pureBreed: "Race pure",
  dontKnow: "Je ne sais pas",
  small: "Petit",
  medium: "Moyen",
  big: "Grand",
  dosntMetter: "N'a pas d'importance",
  male: "Mâle",
  female: "Femelle",
  profile: "Profil",
  save: "sauvegarder",
  doyouwanttosaveit: "Voulez-vous le sauvegarder?",
  ok: "D'accord",
  months: "Meses",
  years: "Années",
  videoAlertTitle:"Pardon",
  videoAlerttxt:"La durée de la vidéo doit être inférieure à 7 secondes",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
es: {
  alert1: "Por favor revisa tu internet",
  internetIssue: "Problema de internet",
  interest: "Interes",
  pet: "mascota",
  deleteImage: "Borrar la imagen",
  delete: "Borrar",
  cancel: "Cancelar",
  youNeedToHAveAtLeastOneImage: "Necesitas tener al menos una imagen",
  profile: "Perfil",
  save: "Guardar",
  petImages: "Imágenes de mascotas",
  petCertificates: "Certificados de mascota",
  petVideo:"Video de mascotas",
  petName: "Nombre de mascota",
  petType: "Tipo de mascota",
  age: "Edad",
  birthDate: "Fecha de nacimiento",
  DatePlace: "aaaa-mm-dd",
  breed: "Raza",
  size: "tamaño",
  sex: "Sexo",
  city: "Ciudad",
  BeriefInfo: "Breve información",
  lookingFor: "Buscando",
  changeInterest: "Cambiar interes",
  addInterest: "Agregar interes",
  bird: "Pájaro",
  cat: "Gato",
  cattle: "Ganado",
  dog: "Perro",
  fish: "Pez",
  horse: "Caballo",
  miniPig: "Mini cerdo",
  rabbit: "Conejo",
  rodent: "Roedor",
  reptile: "Reptil",
  other: "Otro",
  crossBreed: "Híbrido",
  pureBreed: "De pura raza",
  dontKnow: "No se",
  small: "Pequeña",
  medium: "Medio",
  big: "Grande",
  dosntMetter: "No importa",
  male: "Masculino",
  female: "Hembra",
  profile: "Perfil",
  save: "Guardar",
  doyouwanttosaveit: "¿Quieres guardarlo?",
  ok: "DE ACUERDO",
  months: "Meses",
  years: "Años",
  videoAlertTitle:"Lo siento",
  videoAlerttxt:"La duración del video debe ser inferior a 7 segundos",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
sv: {
  alert1: "Vänligen kontrollera din nätverksanslutning",
  internetIssue: "Nätverksproblem",
  interest: "Intresse",
  pet: "Husdjur",
  deleteImage: "Ta bort bilden",
  delete: "Radera",
  cancel: "Avbryt",
  youNeedToHAveAtLeastOneImage: "Du måste ha minst en bild",
  profile: "Profil",
  save: "Spara",
  petImages: "Husdjursbilder",
  petCertificates: "Husdjurscertifikat",
  petVideo:"Husdjurvideo",
  petName: "Husdjurets snamn",
  petType: "Djurtyp",
  age: "Ålder",
  birthDate: "Födelsedatum",
  DatePlace: "åååå-mm-dd",
  breed: "Ras",
  size: "Storlek",
  sex: "Kön",
  city: "Stad",
  BeriefInfo: "Kort information",
  lookingFor: "Söker efter",
  changeInterest: "Ändra intressen",
  addInterest: "Lägg till intressen",
  bird: "Fågel",
  cat: "Katt",
  cattle: "Boskap",
  dog: "Hund",
  fish: "Fisk",
  horse: "Häst",
  miniPig: "Minigris",
  rabbit: "Kanin",
  rodent: "Gnagare",
  reptile: "Reptil",
  other: "Andra",
  crossBreed: "Blandras",
  pureBreed: "Renrasig",
  dontKnow: "Vet inte",
  small: "Liten",
  medium: "Mellan",
  big: "Stor",
  dosntMetter: "Spelar ingen roll",
  male: "Hane",
  female: "Hona",
  profile: "Profil",
  save: "Spara",
  doyouwanttosaveit: "Vill du spara det?",
  ok: "ok",
  months: "Månader",
  years: "år",
  videoAlertTitle:"Tyvärr",
  videoAlerttxt:"Video måste vara kortare än 7 sekunder",
  title:"Välj en film",
  chooseFromLibraryButtonTitle:"Välj från bibliotek...",
  BeriefInfoPlace:"Berätta något om ditt djur"
},
ddr: {
  alert1: "Bitte überprüfen Sie Ihr Internet",
  internetIssue: "Internet-Problem",
  interest: "Interesse",
  pet: "Haustier",
  deleteImage: "Löschen Sie das Bild",
  delete: "Löschen",
  cancel: "Stornieren",
  youNeedToHAveAtLeastOneImage: "Sie müssen mindestens ein Bild haben",
  profile: "Profil",
  save: "sparen",
  petImages: "Pet Bilder",
  petCertificates: "Haustierzertifikate",
  petVideo:"Haustier Video",
  petName: "Haustiername",
  petType: "Haustiertyp",
  age: "Alter",
  birthDate: "Geburtsdatum",
  DatePlace: "JJJJ-MM-TT",
  breed: "Rasse",
  size: "Größe",
  sex: "Sex",
  city: "Stadt",
  BeriefInfo: "Karten Information",
  lookingFor: "Auf der Suche nach",
  changeInterest: "Interesse ändern",
  addInterest: "Interesse hinzufügen",
  bird: "Vogel",
  cat: "Katze",
  cattle: "Das Vieh",
  dog: "Hund",
  fish: "Fisch",
  horse: "Pferd",
  miniPig: "Mini Schwein",
  rabbit: "Hase",
  rodent: "Nagetier",
  reptile: "Reptil",
  other: "Andere",
  crossBreed: "Kreuzung",
  pureBreed: "Reinrassig",
  dontKnow: "Weiß nicht",
  small: "Klein",
  medium: "Mittel",
  big: "Groß",
  dosntMetter: "speillt keine Rolle",
  male: "Männlich",
  female: "Weiblich",
  profile: "Profil",
  save: "sparen",
  doyouwanttosaveit: "Möchten Sie es speichern?",
  ok: "OK",
  months: "Monate",
  years: "Jahre",
  videoAlertTitle:"Es tut uns leid",
  videoAlerttxt:"Die Videodauer muss unter 7 Sekunden liegen",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
ru: {
  alert1: "Пожалуйста, проверьте ваш интернет",
  internetIssue: "Проблемы с сетью",
  interest: "Интерес",
  pet: "Домашнее животное",
  deleteImage: "Удалить фотографию",
  delete: "Удалить",
  cancel: "Oтменить",
  youNeedToHAveAtLeastOneImage: "Вам нужно иметь хотя бы одну фотографию",
  profile: "Профиль",
  save: "Сохранить",
  petImages: "Фотографии домашнего животного",
  petCertificates: "Сертификат домашнего животного",
  petVideo:"Пэт Видео",
  petName: "Имя питомца",
  petType: "Тип питомца",
  age: "Возраст",
  birthDate: "Дата рождения",
  DatePlace: "гггг-мм-дд",
  breed: "Порода",
  size: "Размер",
  sex: "Пол",
  city: "Город",
  BeriefInfo: "Краткая информация",
  lookingFor: "Ищу",
  changeInterest: "Изменить интерес",
  addInterest: "Добавить интерес",
  bird: "Птица",
  cat: "Кошка/Кот",
  cattle: "крупный рогатый скот",
  dog: "Собака",
  fish: "Рыба",
  horse: "Лошадь",
  miniPig: "Мини свинья",
  rabbit: "Кролик",
  rodent: "Грызун",
  reptile: "Рептилия",
  other: "Другие",
  crossBreed: "Помесь",
  pureBreed: "Чистопородный",
  dontKnow: "Не знаю",
  small: "Маленький",
  medium: "Средний",
  big: "Большой",
  dosntMetter: "Не имеет значения",
  male: "Он",
  female: "Она",
  profile: "Профиль",
  save: "Сохранить",
  doyouwanttosaveit: "Вы хотите сохранить это?",
  ok: "Хорошо",
  months: "месяцы",
  years: "лет",
  videoAlertTitle:"сожалею",
  videoAlerttxt:"Продолжительность видео должна быть не более 7 секунд",
  title:"Select a Photo",
  chooseFromLibraryButtonTitle:"Choose from Library...",
  BeriefInfoPlace:"tell us something about your pet",
},
});
export default strings
