import SignInLocalization from 'react-native-localization';

let strings = new SignInLocalization({
 "en-US":{
   enterVarificationCode:"Enter Verification Code",
   alert1:"Something went wrong, Please check your internet",
   alert2:"Email or password doesn't match any account",
   alert3:"Failed Internet issue",
   changingPhoneNumber:"changing phone number",
   internetIssue:"Internet Issue",
   amil:"Email",
   failed:"Failed",
   sending:"Sending",
   sent:"sent",
   password:"Password",
   forgetPassword:"Forgot Password",
   login:"Login",
   continueWithFacebook:"Continue With FaceBook",
   dontHaveAnAccount:"Don't have an account",
   register:"Register",
   enteryouremailaddress: "Enter your e-mail address",

   entercode: "Enter code here",
   verify: "Verify",
   cancel: "Change",
   changephonenumberhere: "Chenge phone number here",
   phonealert: "Phone number is not valid",
   internetissue: "Internet Issue",

   termsofuse: "terms of use",
   privacypolicy: "privacy policy",
   agreetermstext: "By logging in, you agree to our",
   and: "and",


 },
 en:{
  enterVarificationCode:"Enter Verification Code",
  alert1:"Something went wrong, Please check your internet",
  alert2:"Email or password doesn't match any account",
  alert3:"Failed Internet issue",
  changingPhoneNumber:"changing phone number",
  internetIssue:"Internet Issue",
  amil:"Email",
  failed:"Failed",
  sending:"Sending",
  sent:"sent",
  password:"Password",
  forgetPassword:"Forgot Password",
  login:"Login",
  continueWithFacebook:"Continue With FaceBook",
  dontHaveAnAccount:"Don't have an account",
  register:"Register",
  enteryouremailaddress: "Enter your e-mail address",
  entercode: "Enter code here",
  verify: "Verify",
  cancel: "Change",
   changephonenumberhere: "Chenge phone number here",
   phonealert: "Phone number is not valid",
   internetissue: "Internet Issue",
   termsofuse: "terms of use",
   privacypolicy: "privacy policy",
   agreetermstext: "By logging in, you agree to our",
   and: "and",
 },
 it: {
  enterVarificationCode:"Inserisci il codice di verifica",
  alert1:"Qualcosa è andato storto, per favore controlla la tua connessione internet",
  alert2:"Email o password non corrispondono ad alcun account",
  alert3:"Problema di Internet non riuscito",
  changingPhoneNumber:"Cambiare il numero di telefono",
  internetIssue:"Problema Internet",
  amil:"E-mail",
  failed:"Mancato",
  sending:"Sbalgniato",
  sent:"Inviato",
  password:"Parola d'ordine",
  forgetPassword:"Dimenticare la password",
  login:"Accesso",
  continueWithFacebook:"Continua con FaceBook",
  dontHaveAnAccount:"Non avere un account",
  register:"Registrare",
  enteryouremailaddress: "Inserisci il tuo indirizzo email",
  entercode: "Inserire qui il codice",
  verify: "Verificare",
  cancel: "ChengModificaree",
   changephonenumberhere: "Numero di telefono di Chenge qui",
   phonealert: "Il numero di telefono non è valido",
   internetissue: "Problema Internet",

   termsofuse: "condizioni d'uso",
   privacypolicy: "l'informativa sulla privacy.",
   agreetermstext: "Effettuando il login e utilizzando questo servizio, accetti le nostre",
   and: "e",
 },
 fr:{
  enterVarificationCode:"Entrez le code de vérification",
  alert1:"Quelque chose s'est mal passé, s'il vous plaît vérifier votre connexion internet",
  alert2:"Email ou mot de passe ne correspond à aucun compte",
  alert3:"Problème Internet ayant échoué",
  changingPhoneNumber:"Changer de numéro de téléphone",
  internetIssue:"Problème Internet",
  amil:"Email",
  failed:"Échoué",
  sending:"Envoi",
  sent:"Envoyé",
  password:"Mot de passe",
  forgetPassword:"Mot de passe oublié",
  login:"S'identifier",
  continueWithFacebook:"Continuer avec FaceBook",
  dontHaveAnAccount:"Je n'ai pas de compte",
  register:"S'enregistrer",
  
  enteryouremailaddress: "Entrez votre adresse email",
  entercode: "Entrez le code ici",
  verify: "Vérifier",
  cancel: "Changement",
   changephonenumberhere: "Numéro de téléphone de Chenge ici",
   phonealert: "Le numéro de téléphone n'est pas valide",
   internetissue: "Problème Internet",

   termsofuse: "conditions d'utilisation",
   privacypolicy: "politique de confidentialité.",
   agreetermstext: "En vous connectant et en utilisant ce service, vous acceptez nos",
   and: "et notre",
 },
 es:{
  enterVarificationCode:"Introduzca el código de verificación",
  alert1:"Algo salió mal, por favor revisa tu internet",
  alert2:"Correo electrónico o contraseña no coincide con ninguna cuenta",
  alert3:"Error (problema de Internet)",
  changingPhoneNumber:"Cambio de numero de telefono",
  internetIssue:"Problema de internet",
  amil:"Correo electrónico",
  failed:"Ha fallado",
  sending:"Enviando",
  sent:"Enviado",
  password:"Contraseña",
  forgetPassword:"Contraseña olvidada",
  login:"Iniciar sesión",
  continueWithFacebook:"Continuar con FaceBook",
  dontHaveAnAccount:"No tienes cuenta?",
  register:"Registrar",
  enteryouremailaddress: "Ingrese su dirección de correo electrónico",
  entercode: "Ingresa el código aquí",
  verify: "Verificar",
  cancel: "Cambio",
   changephonenumberhere: "Número de teléfono de Chenge aquí.",
   phonealert: "El número de teléfono no es válido",
   internetissue: "Problema de internet",
  

   termsofuse: "términos de uso",
   privacypolicy: "política de privacidad.",
   agreetermstext: "Al iniciar sesión y utilizar este servicio, acepta nuestros",
   and: "y",
 },
 sv:{
  enterVarificationCode:"Ange kod för verifiering",
  alert1:"Något gick snett, vänligen kontrollera din anslutning",
  alert2:"E-post eller lösenord matchar inget konto",
  alert3:"Misslyckades (nätverksproblem)",
  changingPhoneNumber:"Byte av telefonnummer",
  internetIssue:"Nätverksproblem",
  amil:"E-post",
  failed:"Misslyckades",
  sending:"Skickar",
  sent:"skickat",
  password:"Lösenord",
  forgetPassword:"Glömt lösenord",
  login:"Logga in",
  continueWithFacebook:"Fortsätt med FaceBook",
  dontHaveAnAccount:"Har du inget konto?",
  register:"Registrera",
  enteryouremailaddress: "Skriv in din mailadress",
  entercode: "Skriv koden här",
  verify: "Kontrollera",
  cancel: "Byta",
   changephonenumberhere: "Chenge telefonnummer här",
   phonealert: "Telefonnummer är inte giltigt",
   internetissue: "Internetproblem",

   termsofuse: "användarvillkor",
   privacypolicy: "integritetspolicy.",
   agreetermstext: "Genom att logga in och använda denna tjänst godkänner du våra",
   and: "och",
 },
 ddr:{
  enterVarificationCode:"Bestätigungscode eingeben",
  alert1:"Etwas ist schief gelaufen. Bitte überprüfen Sie Ihr Internet",
  alert2:"E-Mail oder Passwort passen zu keinem Konto",
  alert3:"Fehler beim Internet",
  changingPhoneNumber:"Telefonnummer ändern",
  internetIssue:"Internet-Problem",
  amil:"Email",
  failed:"Gescheitert",
  sending:"Senden",
  sent:"gesendet",
  password:"Passwort",
  forgetPassword:"Passwort vergessen",
  login:"Anmeldung",
  continueWithFacebook:"Weiter mit FaceBook",
  dontHaveAnAccount:"Haben Sie noch kein Konto?",
  register:"Registrieren",
  enteryouremailaddress: "Geben sie ihre E-Mailadresse ein",
  entercode: "Code hier eingeben",
  verify: "Überprüfen",
  cancel: "Veränderung",
   changephonenumberhere: "Chenge Telefonnummer hier",
   phonealert: "Telefonnummer ist nicht gültig",
   internetissue: "Internet-Problem",

   termsofuse: "Nutzungsbedingungen",
   privacypolicy: "Datenschutzbestimmungen zu.",
   agreetermstext: "Durch die Anmeldung und Nutzung dieses Dienstes stimmen Sie unseren",
   and: "und",
 },
 ru:{
  enterVarificationCode:"Введите код подтверждения",
  alert1:"Что-то пошло не так, пожалуйста проверьте ваше подключение",
  alert2:"Электронная почта или пароль не совпадает ни к одному аккаунту",
  alert3:"Не удалось, проблема с сетью",
  changingPhoneNumber:"Cмена номера телефона",
  internetIssue:"Проблемы с сетью",
  amil:"Эл. адрес",
  failed:"Не удалось",
  sending:"Отправка",
  sent:"Отправлено",
  password:"Пароль",
  forgetPassword:"Забыл пароль",
  login:"Зайти",
  continueWithFacebook:"Продолжить с FaceBook",
  dontHaveAnAccount:"У вас нет аккаунта?",
  register:"Регистрироваться",
  enteryouremailaddress: "Введите ваш адрес электронной почты",
  entercode: "Введите код сюда",
  verify: "проверить",
  cancel: "+ Изменить",
   changephonenumberhere: "Ченге номер телефона здесь",
   phonealert: "Номер телефона не действителен",
   internetissue: "Интернет-выпуск",

   termsofuse: " условиями использования",
   privacypolicy: "политикой конфиденциальности.",
   agreetermstext: "Входя в систему и используя эту услугу, вы соглашаетесь с нашими",
   and: "и",
 }
});
export default strings