import InterestLocalization from 'react-native-localization';

let strings = new InterestLocalization({
 "en-US":{
   alert1:"Select one or more interest",
   alert2:"something went wrong",
   alert3:"Internet Issue",
   alert4:"Something went wrong",
   pet:"pet",
   interest:"Interest",
   alert5:"Select one or more interest",
   interests:"Interests",
   chooseOneOrMore:"Choose one or more!\nYou can always change it later",
   mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
   setting: "Sitting",
   next: "Next",
   internetissue: "Internet Issue",

 },
 en:{
  alert1:"Select one or more interest",
  alert2:"something went wrong",
  alert3:"Internet Issue",
  alert4:"Something went wrong",
  pet:"pet",
  interest:"Interest",
  alert5:"Select one or more interest",
  interests:"Interests",
  chooseOneOrMore:"Choose one or more!\nYou can always change it later",
  mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
  setting: "Sitting",
  next: "Next",
  internetissue: "Internet Issue",
 },
 it: {
  alert1:"Seleziona uno o più interessi",
  alert2:"Qualcosa è andato storto",
  alert3:"Problema di Internet",
  alert4:"Qualcosa è andato storto",
  pet:"Animali domestici",
  interest:"Interesse",
  alert5:"Seleziona uno o più interessi",
  interests:"Interesse",
  chooseOneOrMore:"Scegli uno o più!\n Puoi sempre cambiarlo più tardi.",
  mate: "Compagno",
   walk: "Camminare",
   meet: "Incontrare",
   talk: "Parlare",
  setting: "Guardia",
  next: "Il prossimo",
  internetissue: "problema di internet",
 },
 fr:{
  alert1:"Sélectionnez un ou plusieurs intérêts",
  alert2:"quelque chose s'est mal passé",
  alert3:"Problème Internet",
  alert4:"Quelque chose a mal tourné",
  pet:"animal de compagnie",
  interest:"Intérêt",
  alert5:"Sélectionnez un ou plusieurs intérêts",
  interests:"Intérêts",
  chooseOneOrMore:"Choisissez un ou plusieurs!\n Vous pouvez toujours le changer plus tard.",
  mate: "Camarade",
   walk: "Marche",
   meet: "Rencontrer",
   talk: "Parler",
  setting: "Séance",
  next: "Suivant",
  internetissue: "problème internet",
 },
 es:{
  alert1:"Seleccione uno o más intereses",
  alert2:"Algo salió mal",
  alert3:"Problema de internet",
  alert4:"Algo salió mal",
  pet:"Mascota",
  interest:"Interés",
  alert5:"Seleccione uno o más intereses",
  interests:"Intereses",
  chooseOneOrMore:"¡Elige uno o más!\n Siempre puedes cambiarlo más tarde.",
  mate: "Compañero",
   walk: "Caminar",
   meet: "Reunirse",
   talk: "Hablar",
  setting: "Cuidado de animales",
  next: "Siguiente",
  internetissue: "problema de internet",
 },
 sv:{
  alert1:"Välj ett eller flera intressen",
  alert2:"Något gick snett",
  alert3:"Nätverksproblem",
  alert4:"Något gick snett",
  pet:"Husdjur",
  interest:"Intresse",
  alert5:"Välj ett eller flera intressen",
  interests:"Intressen",
  chooseOneOrMore:"Välj ett eller flera!\nDu kan alltid ändra senare.",
  mate: "Para",
   walk: "Promenad",
   meet: "Träffa",
   talk: "Prata",
  setting: "Passning",
  next: "Nästa",
  internetissue: "internet problem",
 },
 ddr:{
  alert1:"Wählen Sie ein oder mehrere Interessen aus",
  alert2:"Etwas ist schief gelaufen",
  alert3:"Internet-Problem",
  alert4:"Etwas ist schief gelaufen",
  pet:"Haustier",
  interest:"Interesse",
  alert5:"Wählen Sie ein oder mehrere Interessen aus",
  interests:"Interessen",
  chooseOneOrMore:"Wählen Sie eine oder mehrere!\n Sie können es später jederzeit ändern.",
  mate: "Kamerad",
   walk: "Gehen",
   meet: "Treffen",
   talk: "Sich unterhalten",
  setting: "Aufpassen",
  next: "Nächste",
  internetissue: "Internet-Problem",
 },
 ru:{
  alert1:" Выберите один или несколько интересов",
  alert2:"Что-то пошло не так",
  alert3:"Проблемы с сетью",
  alert4:"Что-то пошло не так",
  pet:"Домашнее животное",
  interest:"Интерес",
  alert5:"Выберите один или несколько интересов",
  interests:"Интересы",
  chooseOneOrMore:"Выберите один или несколько!\n Вы всегда можете изменить это позже.",
  mate: "Приятель",
   walk: "Ходить",
   meet: "Встретить",
   talk: "Говорить",
  setting: "Присмотр",
  next: "Следующий",
  internetissue: "проблема интернета",
 }
});
export default strings
