import SignUpLocalization from 'react-native-localization';

let strings = new SignUpLocalization({
 "en-US":{
   enterVarificationCode:"Enter Verification Code",
   alert1:"Phone Number is not valid",
   alert2:"Please fill all fields",
   alert3:"Please enter minimum eight character of password",
   alert4:"Password doesn't match",
   alert5:"Email is not correct",
   alert6:"Internet issue",
   failed:"Failed",
   sending:"Sending",
   sent:"Sent",
   changingPhoneNumber:"changing phone number",
   informationAboutYou:"Information About You",
   fullName:"Full Name",
   city:"City",
   mobileNumber:"Mobile Number",
   email:"E-mail",
   password:"Password",
   confirmPassword:"Confirm Password",
   register:"Register",
   haveAnAccount:"Have an account",
   login:"Login",
   enteryourfullname:"Enter your full name",
   enteryouremailaddress: "Enter your e-mail address",
   pleaseconfirmyourpassword: "Please confirm your password",
   entercode: "Enter code here",
   verify: "Verify",
   cancel: "Change",
   changephonenumberhere: "Change phone number here",
   phonealert: "Phone number is not valid",
   or: "Or",
   codesentto: "Code send to",

   termsofuse: "terms of use",
   privacypolicy: "privacy policy",
   agreetermstext: "By logging in, you agree to our",
   and: "and",
   locationAlert: "Please turn on location from setting",
   noLocation:"no location",
 },
 en:{
  enterVarificationCode:"Enter Verification Code",
  alert1:"Phone Number is not valid",
  alert2:"Please fill all fields",
  alert3:"Please enter minimum eight character of password",
  alert4:"Password doesn't match",
  alert5:"Email is not correct",
  alert6:"Internet issue",
  failed:"Failed",
  sending:"Sending",
  sent:"Sent",
  changingPhoneNumber:"changing phone number",
  informationAboutYou:"Information About You",
  fullName:"Full Name",
  city:"City",
  mobileNumber:"Mobile Number",
  email:"E-mail",
  password:"Password",
  confirmPassword:"Confirm Password",
  register:"Register",
  haveAnAccount:"Have an account",
  login:"Login",
  enteryourfullname:"Enter your full name",
   enteryouremailaddress: "Enter your e-mail address",
   pleaseconfirmyourpassword: "Please confirm your password",
   entercode: "Enter code here",
   verify: "Verify",
   cancel: "Change",
   changephonenumberhere: "Change phone number here",
   phonealert: "Phone number is not valid",
   or: "Or",
   codesentto: "Code send to",

   termsofuse: "terms of use",
   privacypolicy: "privacy policy",
   agreetermstext: "By logging in, you agree to our",
   and: "and",
   locationAlert: "Please turn on location from setting",
   noLocation:"no location",
 },
 it: {
  enterVarificationCode:"Inserisci il codice di verifica",
  alert1:"Il numero di telefono non è valido",
  alert2:"Per favore riempi tutti i campi",
  alert3:"Si prega di inserire un minimo di otto caratteri di password",
  alert4:"La password non corrisponde",
  alert5:"L'email non è corretta",
  alert6:"Problema di Internet",
  failed:"Mancato",
  sending:"Invio",
  sent:"Inviato",
  changingPhoneNumber:"Cambiare il numero di telefono",
  informationAboutYou:"Informazioni su di te",
  fullName:"Nome e cognome",
  city:"Città",
  mobileNumber:"Numero di cellulare",
  email:"E-mail",
  password:"Parola d'ordine",
  confirmPassword:"Conferma password",
  register:"Registrare",
  haveAnAccount:"Hai un conto",
  login:"Accesso",
  
  enteryourfullname:"Inserisci il tuo nome e cognome",
   enteryouremailaddress: "Inserisci il tuo indirizzo email",
   pleaseconfirmyourpassword: "Per favore conferma la tua password",
   entercode: "Inserire qui il codice",
   verify: "Verificare",
   cancel: "ChengModificaree",
   changephonenumberhere: "Cambia il numero di telefono qui",
   phonealert: "Il numero di telefono non è valido",
   or: "O",
   codesentto: "Il codice invia a",

   termsofuse: "condizioni d'uso",
   privacypolicy: "l'informativa sulla privacy.",
   agreetermstext: "Effettuando il login e utilizzando questo servizio, accetti le nostre",
   and: "e",
   locationAlert: "Attiva la posizione dall'impostazione",
   noLocation:"Nessuna posizione",
 },
 fr:{
  enterVarificationCode:"Entrez le code de vérification",
  alert1:"Merci de compléter tous les champs",
  alert2:"Merci de compléter tous les champs",
  alert3:"Veuillez entrer au moins huit caractères pour le mot de passe",
  alert4:"Le mot de passe ne correspond pas au précédent",
  alert5:"L'email n'est pas correct",
  alert6:"Problème Internet",
  failed:"Échoué",
  sending:"Envoi",
  sent:"Envoyé",
  changingPhoneNumber:"Changer de numéro de téléphone",
  informationAboutYou:"Informations sur vous",
  fullName:"Nom complet",
  city:"Ville",
  mobileNumber:"Numéro de portable",
  email:"Email",
  password:"Mot de passe",
  confirmPassword:"Confirmez le mot de passe",
  register:"S'enregistrer",
  haveAnAccount:"Avez-vous un compte ?",
  login:"S'identifier",
  
  enteryourfullname:"Entrez votre nom complet",
   enteryouremailaddress: "Entrez votre adresse email",
   pleaseconfirmyourpassword: "Veuillez confirmer votre mot de passe",
   entercode: "Entrez le code ici",
   verify: "Vérifier",
   cancel: "Changement",
   changephonenumberhere: "Changer le numéro de téléphone ici",
   phonealert: "Le numéro de téléphone n'est pas valide",
   or: "Ou",
   codesentto: "Code envoyé à",

   termsofuse: "conditions d'utilisation",
   privacypolicy: "politique de confidentialité.",
   agreetermstext: "En vous connectant et en utilisant ce service, vous acceptez nos",
   and: "et notre",
   locationAlert: "Veuillez activer l'emplacement à partir du réglage",
   noLocation:"pas d'emplacement",
 },
 es:{
  enterVarificationCode:"Ingrese el código de verificación",
  alert1:"Número de teléfono no válido",
  alert2:"Por favor llena todos los espacios",
  alert3:"Por favor, ingrese un mínimo de ocho signos de contraseña",
  alert4:"La contraseña no coincide",
  alert5:"Correo electrónico no correcto",
  alert6:"Problema de internet",
  failed:"Ha fallado",
  sending:"Enviando",
  sent:"Expedido",
  changingPhoneNumber:"Cambio de número de teléfono",
  informationAboutYou:"Información acerca de ti",
  fullName:"Nombre completo",
  city:"Ciudad",
  mobileNumber:"Número de teléfono móvil",
  email:"Correo electrónico ",
  password:"Contraseña",
  confirmPassword:"Confirmar contraseña",
  register:"Registrar",
  haveAnAccount:"Teienes una cuenta?",
  login:"Iniciar sesión",
  
  enteryourfullname:"Ingrese su nombre completo",
   enteryouremailaddress: "Ingrese su dirección de correo electrónico",
   pleaseconfirmyourpassword: "Por favor, confirme su contraseña",
   entercode: "Ingresa el código aquí",
   verify: "Verificar",
   cancel: "Cambio",
   changephonenumberhere: "Cambia el número de teléfono aquí",
   phonealert: "El número de teléfono no es válido",
   or: "O",
   codesentto: "Código enviado a",

   termsofuse: "términos de uso",
   privacypolicy: "política de privacidad.",
   agreetermstext: "Al iniciar sesión y utilizar este servicio, acepta nuestros",
   and: "y",
   locationAlert: "Activa la ubicación desde la configuración",
   noLocation:"Sin ubicacion",
 },
 sv:{
  enterVarificationCode:"Ange kod för verifiering",
  alert1:"Ogiltigt telefonnummer",
  alert2:"Vänligen fyll i alla fält",
  alert3:"Ange ett lösenord på minst 8 tecken",
  alert4:"Lösenorden matchar inte",
  alert5:"Felaktig e-post",
  alert6:"Nätverksproblem",
  failed:"Misslyckades",
  sending:"Skickar",
  sent:"Skickat",
  changingPhoneNumber:"Ändra telefonnummer",
  informationAboutYou:"Information om dig",
  fullName:"Fullständigt namn",
  city:"Stad",
  mobileNumber:"Mobilnummer",
  email:"E-post",
  password:"Lösenord",
  confirmPassword:"Bekräfta lösenord",
  register:"Registrera",
  haveAnAccount:"Har du ett konto?",
  login:"Logga in",
  
  enteryourfullname:"Ange ditt fullständiga namn",
   enteryouremailaddress: "Skriv in din mailadress",
   pleaseconfirmyourpassword: "Vänligen bekräfta ditt lösenord",
   entercode: "Skriv koden här",
   verify: "Kontrollera",
   cancel: "Byta",
   changephonenumberhere: "Ändra telefonnummer här",
   phonealert: "Telefonnummer är inte giltigt",
   or: "Eller",
   codesentto: "Kod skickas till",

   termsofuse: "användarvillkor",
   privacypolicy: "integritetspolicy.",
   agreetermstext: "Genom att logga in och använda denna tjänst godkänner du våra",
   and: "och",
   locationAlert: "Vänligen aktivera plats från inställningen",
   noLocation:"Ingen plats",
 },
 ddr:{
  enterVarificationCode:"Bestätigungscode eingeben",
  alert1:"Ungültige Telefonnumer",
  alert2:"Bitte alle Felder ausfüllen",
  alert3:"Bitte geben Sie ein Passwort mit mindestens acht Zeichen ein",
  alert4:"Passwort stimmt nicht überein",
  alert5:"E-Mail ist nicht korrekt",
  alert6:"Internet-Problem",
  failed:"Gescheitert",
  sending:"Senden",
  sent:"Geschickt",
  changingPhoneNumber:"Telefonnummer ändern",
  informationAboutYou:"Informationen über dich",
  fullName:"Vollständiger Name",
  city:"Stadt",
  mobileNumber:"Handynummer",
  email:"Email",
  password:"Passwort",
  confirmPassword:"Passwort bestätigen",
  register:"Registrieren",
  haveAnAccount:"Haben Sie ein Konto ",
  login:"Anmeldung",
  
  enteryourfullname:"Geben Sie Ihren vollständigen Namen ein",
   enteryouremailaddress: "Geben sie ihre E-Mailadresse ein",
   pleaseconfirmyourpassword: "Bitte bestätigen Sie Ihr Passwort",
   entercode: "Code hier eingeben",
   verify: "Überprüfen",
   cancel: "Veränderung",
   changephonenumberhere: "Ändern Sie hier die Telefonnummer",
   phonealert: "Telefonnummer ist nicht gültig",
   or: "Oder",
   codesentto: "Code senden an",

   termsofuse: "Nutzungsbedingungen",
   privacypolicy: "Datenschutzbestimmungen zu.",
   agreetermstext: "Durch die Anmeldung und Nutzung dieses Dienstes stimmen Sie unseren",
   and: "und",
   locationAlert: "Bitte schalten Sie den Standort von der Einstellung ein",
   noLocation:"Kein Platz",
 },
 ru:{
  enterVarificationCode:"Введите код подтверждения",
  alert1:"Недействительный мобильный номер",
  alert2:"Пожалуйста заполните все поля",
  alert3:"Пожалуйста, введите минимум восемь символов пароля",
  alert4:"Пароль не совпадает",
  alert5:"Эл. адрес неправильный",
  alert6:"Проблемы с сетью",
  failed:"Не удалось",
  sending:"Отправка",
  sent:"Отправлено",
  changingPhoneNumber:"Смена номера телефона",
  informationAboutYou:"Информация о вас",
  fullName:"Полное имя",
  city:"Город",
  mobileNumber:"Мобильный номер",
  email:"Эл. адрес",
  password:"Пароль",
  confirmPassword:"Подтвердите пароль",
  register:"Регистрироваться",
  haveAnAccount:"У вас есть аккаунт?",
  login:"Зайти",
  
  enteryourfullname:"Введите свое полное имя",
   enteryouremailaddress: "Введите ваш адрес электронной почты",
   pleaseconfirmyourpassword: "Пожалуйста, подтвердите ваш пароль",
   entercode: "Введите код сюда",
   verify: "проверить",
   cancel: "+ Изменить",
   changephonenumberhere: "Сменить номер телефона здесь",
   phonealert: "Номер телефона не действителен",
   or: "Или же",
   codesentto: "Код отправить",

   termsofuse: " условиями использования",
   privacypolicy: "политикой конфиденциальности.",
   agreetermstext: "Входя в систему и используя эту услугу, вы соглашаетесь с нашими",
   and: "и",
   locationAlert: "Пожалуйста, включите местоположение из настроек",
   noLocation:"Нет места",
 }
});
export default strings