import InquiryLocalization from 'react-native-localization';

let strings = new InquiryLocalization({
 "en-US":{
   placeHolder1:"Type your full name",
   placeHolder2:"Type your email",
   placeHolder3:"Enter subject here",
   placeHolder4:"Enter your text here",
   sendingMail:"Sending email",
   alert:"Email is not correct",
   alert2:"Something is missing",
   internetIssue:"Internet Issue",
   success:"Success",
   emailSent:"Email Sent",
   EmailIsNotValid:"Email is not valid",
   name:"Name",
   email: "Email",
   title: "Title",
   inquiry: "Inquiry",
   maximum200Characters: "maximum 200 characters",
   report: "Report",
 },
 en:{
  placeHolder1:"Type your full name",
  placeHolder2:"Type your email",
  placeHolder3:"Enter subject here",
  placeHolder4:"Enter your text here",
  sendingMail:"Sending email",
  alert:"Email is not correct",
  alert2:"Something is missing",
  internetIssue:"Internet Issue",
  success:"Success",
  emailSent:"Email Sent",
  EmailIsNotValid:"Email is not valid",
  name:"Name",
  email: "Email",
  title: "Title",
  inquiry: "Inquiry",
  maximum200Characters: "maximum 200 characters",
  report: "Report",
 },
 it: {
  placeHolder1:"Scrivi il tuo nome e congnome",
  placeHolder2:"Inserisci la tua email",
  placeHolder3:"Inserisci qui il tuo titolo",
  placeHolder4:"Inserisci qui il tuo testo",
  sendingMail:"Invio di posta",
  alert:"L'email non è corretta",
  alert2:"Manca qualcosa",
  internetIssue:"Problema di Internet",
  success:"Successo",
  emailSent:"Email inviata",
  EmailIsNotValid:"L'email non è valida",
  name:"Nome",
  email: "E-mail",
  title: "Titolo",
  inquiry: "Richiesta",
  maximum200Characters: "Massimo 200 caratteri",
  report: "Rapporto",
 },
 fr:{
  placeHolder1:"Tapez votre nom complet",
  placeHolder2:"Tapez votre email",
  placeHolder3:"Entrez votre titre ici",
  placeHolder4:"Entrez votre texte ici",
  sendingMail:"Envoi de mail",
  alert:"L'email n'est pas correct",
  alert2:"Un champ est manquant",
  internetIssue:"Problème Internet",
  success:"Succès",
  emailSent:"Email envoyé",
  EmailIsNotValid:"L'email n'est pas valide",
  name:"Nom",
  email: "Titre",
  title: "Titre",
  inquiry: "Enquête",
  maximum200Characters: "maximum 200 caractères",
  report: "Signaler",
 },
 es:{
  placeHolder1:"Escriba su nombre completo",
  placeHolder2:"Escribe tu correo electrónico",
  placeHolder3:"Ingrese su título aquí",
  placeHolder4:"Escriba su texto aquí",
  sendingMail:"Enviando correo electrónico",
  alert:"El correo electrónico no es correcto",
  alert2:"Algo falta",
  internetIssue:"Problema de internet",
  success:"Éxito",
  emailSent:"Correo electrónico enviado",
  EmailIsNotValid:"Correo electrónico válido",
  name:"Nombre",
  email: "Correo electrónico",
  title: "Título",
  inquiry: "Pregunta",
  maximum200Characters: "Máximo 200 letras",
  report: "Informe",
 },
 sv:{
  placeHolder1:"Ange ditt fullständiga namn",
  placeHolder2:"Ange din e-post",
  placeHolder3:"Ange ämne här",
  placeHolder4:"Skriv din text här",
  sendingMail:"Skickar e-post",
  alert:"Felaktig e-post",
  alert2:"Något saknas",
  internetIssue:"Nätverksproblem",
  success:"Lyckat",
  emailSent:"E-post skickad",
  EmailIsNotValid:"Ogiltig e-post",
  name:"Namn",
  email: "E-post",
  title: "Ämne",
  inquiry: "Förfrågan",
  maximum200Characters: "Max 200 tecken",
  report: "Rapportera",
 },
 ddr:{
  placeHolder1:"Geben Sie Ihren vollständigen Namen ein",
  placeHolder2:"Geben Sie Ihre E-Mail ein",
  placeHolder3:"Geben Sie hier Ihren Titel ein",
  placeHolder4:"Schreiben SieIhren Text hier ein",
  sendingMail:"Nachrichten senden",
  alert:"E-Mail ist nicht korrekt",
  alert2:"Etwas fehlt",
  internetIssue:"Internet-Problem",
  success:"Erfolgreich",
  emailSent:"E-Mail gesendet",
  EmailIsNotValid:"Email ist ungültig",
  name:"Name",
  email: "Email",
  title: "Titel",
  inquiry: "Anfrage",
  maximum200Characters: "Maximal 200 Zeichen",
  report: "Bericht",
 },
 ru:{
  placeHolder1:"Введите свое полное имя",
  placeHolder2:"Введите адрес электронной почты",
  placeHolder3:"Введите тему здесь",
  placeHolder4:"Введите свой текст здесь",
  sendingMail:"Отправка электронной почты",
  alert:"Эл. адрес не правильный",
  alert2:"Чего-то не хватает",
  internetIssue:"Проблема интернета",
  success:"Успех",
  emailSent:"Письмо отправлено",
  EmailIsNotValid:"Эл. адрес не является допустимым",
  name:"Имя",
  email: "Эл. адрес",
  title: "Темa",
  inquiry: "Запрос",
  maximum200Characters: "Максимум 200 символов",
  report: "Пожаловаться",
 }
});
export default strings



