import ParanuGuideLocalization from 'react-native-localization';

let strings = new ParanuGuideLocalization({
 "en":{
   guide:"FAQ",
   paranuOverView:"Paranu overview",
   whatIsParanu:"What is Paranu",
   paranuInfoParagraph1Line1: "Paranu is the world's largest dating site to meet new partners for your animal. Think of us like a dating site for people, but this is for animals.",
   paranuInfoParagraph1Line2: " Are you here to meet a partner for your animal, a walk buddy or a friend for your animal? Then you have come to the right place. We are the world's best animal dating site for an important reason. We love all animals regardless of race or mixed breed. Everyone is equally worthy for us!",
   paranuInfoParagraph1Line3: "Welcome to Paranu, world's largest dating site for animals, ONLY animals.",
   paranuInfoParagraph1Line4: " Download the Paranu app for iOS and Android or visit Para.nu on the web.",
   question1:"How do I use Paranu?",
   answer1Line1: "You can download the Paranu app for iOS and Android or go to Para.nu to use Paranu on the web.",
   answer1Line11:"Swipe. Match. Chat. Meet. Paranu is fun and simple. Swipe right to like somebody, swipe left to 'pass'. If someone likes you pet too, it's a match! Two animals match if both are interested. Just swipe, match and chat online with your matches, then plan what comes next!",
   question2: "Can I use Paranu anywhere in the world",
   answer2: "Paranu is a global online dating platform for animals in over 190 countries.",
   signUpAndGetStarted: "Sign up and get started",

   question3: "How do I create a Paranu account?",
   answer3: "Download the Paranu app for iOS and Android or visit Para.nu and follow the directions. It's super easy.",
   question4: "Can I register without Facebook?",
   answer4: "You can of course register without Facebook through your email address and phone number.",
  matchingAndMessage:"Matching and message",
   question5: "Can I search for a certain person at Paranu?",
   answer5: "Yes, if you know who the pet owner is, just touch the magnifying glass and fill in the user ID.",
   question6: "How do I send a message to someone?",
   answer6: "As the world's largest dating app for animals, you can chat with other local animal owners wherever you are. However, only users who have specified mutual interests have the possibility to match and thereby also chat. If you have not yet received a match, just continue swiping! It's just a matter of time before it happens!",
   question7: "Can I message a user unless we have matched?",
   answer7: "No, for the sake of the privacy of our users, it is not possible to send a message to a user unless there has been a match.",
   //question8: "I have not matched with anyone, what should I do?",
   //answer8: "You can always try to increase the distance and then continue swiping It is only a matter of time before it happens!",
   
   question9: "How do I report someone?",
   answer10: "You can report users that you think misbehave, go to the profile of the person > touch the triangular icon (warning icon) > Report.",

   

 },

 it: {
  guide:"FAQ",
  paranuOverView:"Panoramica di Paranu",
  whatIsParanu:"Cos'è Paranu?",
  paranuInfoParagraph1Line1: "Paranu è il sito di incontri più grande del mondo per incontrare nuovi partner per il tuo animale. Pensate a noi come a un sito di incontri per persone, ma questo è per gli animali.",
  paranuInfoParagraph1Line2: "Sei qui per incontrare un partner per il tuo animale, un compagno o un amico per il tuo animale? Allora sei arrivato nel posto giusto. Siamo il miglior sito di incontri di animali al mondo per una ragione importante. Amiamo tutti gli animali indipendentemente dalla razza o dalla razza mista. Tutti sono ugualmente degni di noi!",
  paranuInfoParagraph1Line3: "Benvenuti a Paranu, il sito di incontri per animali più grande del mondo, SOLO animali.",
  paranuInfoParagraph1Line4: "Scarica l'app Paranu per iOS e Android o visita Para.nu sul web.",
  question1:"Come si usa Paranu?",
  answer1Line1: "Puoi scaricare l'app Paranu per iOS e Android o andare su Para.nu per usare Paranu sul web.",
  answer1Line11:"Scorre. Correspondono. Chiacchierare. Incontrare. Paranu è divertente e semplice. Scorri verso destra per far piacere a qualcuno, scorri verso sinistra per passare.Se a qualcuno piaci anche l'animale domestico, è una partita! Due animali corrispondono se entrambi sono interessati.Basta scorrere, abbinare e chattare online con le partite, quindi pianificare ciò che viene dopo!",
  answer1Line2: "Paranu attualmente supporta iOS 8 e versioni successive, Android 4.4 e versioni successive e le versioni più recenti di tutti i browser più comuni (Internet Explorer, Chrome, Firefox, Safari e così via).",
  question2: "Posso usare Paranu in qualsiasi parte del mondo?",
  answer2: "Paranu è una piattaforma di incontri online globale per animali in oltre 190 paesi.",
  signUpAndGetStarted: "Iscriviti e inizia",

  question3: "Come creo un account Paranu?",
  answer3: "Scarica l'app Paranu per iOS e Android o visita Para.nu e segui le istruzioni. È super facile",
  question4: "Posso registrarmi senza Facebook?",
  answer4: "Naturalmente puoi registrarti senza Facebook tramite il tuo indirizzo e-mail e il numero di telefono.",
  matchingAndMessage:"Corrispondenza e messaggio",
  question5: "Posso cercare una certa persona a Paranu?",
  answer5: "Sì, se sai chi è il proprietario dell'animale, tocca la lente d'ingrandimento e inserisci il user ID.",
  question6: "Come posso inviare un messaggio a qualcuno?",
  answer6: "Come la più grande app di appuntamenti al mondo per animali, puoi chiaccherare con altri proprietari di animali locali ovunque tu sia. Tuttavia, solo gli utenti che hanno specificato interessi reciproci hanno la possibilità di abbinare e quindi anche di chiaccherare. Se non hai ancora ricevuto una partita, continua a scorrere! È solo una questione di tempo prima che accada!",
  question7: "Posso inviare un messaggio a un utente a meno che non ci sia una corrispondenza?",
  answer7: "No, per il rispetto della privacy dei nostri utenti, non è possibile inviare un messaggio a un utente a meno che non ci sia statouna partita.",
  //question8: "Non ho abbinato nessuno, cosa dovrei fare?",
  //answer8: "Puoi sempre provare ad aumentare la distanza e poi continuare a strisciare È solo questione di tempo prima che accada!",
  question9: "Come faccio a segnalare qualcuno?",
   answer10: "Puoi segnalare agli utenti che ritieni che si comportino male, vai al profilo della persona> tocca il triangolare icona (icona di avviso)> Segnala.", 
   
   
  },
 fr:{
  guide:"FAQ",
  paranuOverView:"Vue d'ensemble sur Paranu",
  whatIsParanu:"Qu'est-ce que Paranu?",
  paranuInfoParagraph1Line1: "Paranu est le plus grand site de rencontres au monde pour rencontrer de nouveaux partenaires pour votre animal. Une sorte de site de rencontres, mais pour les animaux quoi!",
  paranuInfoParagraph1Line2: "Êtes-vous ici pour rencontrer un partenaire pour votre animal, un compagnon de promenade, un ami pour votre animal? Alors vous êtes au bon endroit. Nous sommes le meilleur site de rencontre d'animaux au monde pour une raison importante. Nous aimons tous les animaux, peu importe qu'ils soient de pure race ou croisés. Ils sont tous pareils et nous les aimons inconditionnellement.",
  paranuInfoParagraph1Line3: "Bienvenue sur Paranu, le plus grand site de rencontres au monde réservé aux animaux.",
  paranuInfoParagraph1Line4: "Téléchargez l'application Paranu pour iOS et Android ou visitez Para.nu sur le Web.",
  question1:"Comment puis-je utiliser Paranu?",
  answer1Line1: "Vous pouvez télécharger l'application Paranu pour iOS et Android ou vous rendre sur Para.nu pour utiliser Paranu sur le Web.",
  answer1Line11:"Swiper. Matcher. Papoter. Rencontrer. Paranu est simple et amusant. Swipez vers la droite pour aimer quelqu'un et vers la gauche pour passer. Si quelqu'un vous aime aussi, c'est un match! Il suffit de swiper, de matcher et de discuter en ligne avec vos matchs pour parler de ce que vous pourrez faire dans la vraie vie !",
  answer1Line2: "Paranu prend actuellement en charge iOS 8 et versions ultérieures, Android 4.4 et versions ultérieures ainsi que les dernières versions de tous les navigateurs les plus courants (Internet Explorer, Chrome, Firefox, Safari, etc.).",
  question2: "Puis-je utiliser Paranu n'importe où dans le monde?",
  answer2: "Paranu est une plateforme mondiale de rencontres en ligne pour les animaux, présente dans plus de 190 pays.",
  signUpAndGetStarted: "Inscrivez-vous et commencez",

  question3: "Comment créer un compte Paranu?",
  answer3: "Téléchargez l'application Paranu pour iOS et Android ou visitez Para.nu Et suivez les instructions. C'est super facile.",
  question4: "Puis-je m'inscrire sans Facebook?",
  answer4: "Vous pouvez bien sûr vous inscrire sans Facebook via votre adresse email et votre numéro de téléphone.",
  matchingAndMessage:"Correspondance et message",
  question5: "Puis-je rechercher une certaine personne chez Paranu?",
  answer5: "Oui, si vous connaissez le propriétaire de l'animal, il vous suffit de cliquer sur la loupe et de saisir son user ID.",
  question6: "Comment puis-je envoyer un message à quelqu'un",
  answer6: "En tant qu'application de rencontres pour animaux la plus grande au monde, vous pouvez discuter avec d'autres propriétaires d'animaux locaux où que vous soyez. Cependant, seuls les utilisateurs qui sont un match peuvent chatter. Si vous n'avez encore reçu aucun match , continuez simplement à swiper! C'est juste une question de temps avant que ça n'arrive!",
  question7: "Puis-je envoyer un message à un utilisateur sauf si nous avons apparié?",
  answer7: "Non, dans l’intérêt de la vie privée de nos utilisateurs, il n’est pas possible d’envoyer un message à un utilisateur sans queun match.",
  //question8: "Je n'ai jumelé à personne, que dois-je faire?",
  //answer8: "Vous pouvez toujours essayer d'augmenter la distance et ensuite continuer à glisser. Ce n'est qu'une question de temps avant que cela ne se produise!",
  question9: "Comment signaler quelqu'un?",
   answer10: "Vous pouvez signaler un  utilisateur que vous pensez se conduire mal, accédez au profil de la personne> Cliquez sur l'icône triangulaire (icône pour signaler) > Signaler.",
   
  },
es:{
  guide:"Preguntas más frecuentes",
  paranuOverView:"Descripción general de Paranu",
  whatIsParanu:"¿Qué es Paranu?",
  paranuInfoParagraph1Line1: "Paranu es el sitio de citas más grande del mundo para conocer nuevas parejas para tu animal. Piensa en nosotros como un sitio de citas para personas, pero esto es para animales.",
  paranuInfoParagraph1Line2: "¿Estás aquí para encontrar una pareja para tu animal, un compañero de paseo o un amigo para tu animal? Entonces has venido al lugar correcto.Somos el mejor sitio de citas de animales del mundo por una razón importante.Amamos a todos los animales sin importar raza o raza mixta. ¡Todos son igualmente dignos para nosotros!",
  paranuInfoParagraph1Line3: "Bienvenido a Paranu, el sitio de citas para animales más grande del mundo, SOLO animales.",
  paranuInfoParagraph1Line4: "Descargue la aplicación Paranu para iOS y Android o visite Para.nu en la reb.",
  question1:"¿Cómo uso Paranu?",
  answer1Line1: "Puede descargar la aplicación Paranu para iOS y Android o ir a Para.nu para usar Paranu en la reb.",
  answer1Line11:"Desliza. Empareja. Charla. Encontrarce. Paranu es divertido y simple. Desliza a la derecha para que te guste alguien, desliza a la izquierda para 'pasar'. Si a alguien le gusta tu mascota también, ¡es un partido! Dos animales coinciden si ambos están interesados. Simplemente desliza, empareja y chatea en línea con tus emparejaciones, luego planifica lo que sigue.",
  answer1Line2: "Paranu actualmente es compatible con iOS 8 y superior, Android 4.4 y superior y las últimas versiones de los navegadores más comunes (Internet Explorer, Chrome, Firefox, Safari, etc.).",
  question2: "¿Puedo usar Paranu en cualquier parte del mundo?",
  answer2: "Paranu es una plataforma global de citas en línea para animales en más de 190 países.",
  signUpAndGetStarted: "Regístrate y empieza",

  question3: "¿Cómo creo una cuenta de Paranu?",
  answer3: "Descargue la aplicación Paranu para iOS y Android o visite Para.nu y siga las instrucciones. Es super facil.",
  question4: "¿Puedo registrarme sin Facebook?",
  answer4: "Por supuesto, puede registrarse sin Facebook a través de su dirección de correo electrónico y número de teléfono.",
  matchingAndMessage:"Emparejo y mensaje",
  question5: "¿Puedo buscar una determinada persona en Paranu?",
  answer5: "Sí, si sabes quién es el dueño de la mascota, solo toca la lupa y escribe el user ID.",
  question6: "¿Cómo envío un mensaje a alguien?",
  answer6: "Como la aplicación de citas para animales más grande del mundo, puedes chatear con otros propietarios de animales locales en cualquier lugar usted está. Sin embargo, solo los usuarios que han especificado intereses mutuos tienen la posibilidad de emparejarse y, por lo tanto, también chatear. Si aún no ha recibido una emparejacion, ¡solo continúe deslizando! Es solo cuestión de tiempo antes que suceda!",
  question7: "¿Puedo enviar un mensaje a un usuario a menos que hayamos coincidido?",
  answer7: "No, por el bien de la privacidad de nuestros usuarios, no es posible enviar un mensaje a un usuario a menos que haya habidoun partido.",
  //question8: "No he emparejado con nadie, ¿qué debo hacer?",
  //answer8: "Siempre puedes intentar aumentar la distancia y luego continuar deslizando. ¡Es solo cuestión de tiempo antes de que suceda!",
  question9: "¿Cómo denuncio a alguien?",
   answer10: "Puede reportar a los usuarios que se portan mal, ve al perfil de la persona> toque el icono triángular (icono de advertencia)> Reportar.",
   
   
  },
sv:{
  guide:"Vanliga frågor",
  paranuOverView:"Paranu översikt",
  whatIsParanu:"Vad är Paranu?",
  paranuInfoParagraph1Line1: "Paranu är världens största datingsida för att träffa nya partners till ditt djur. Tänk på oss som en datingsida för människor, men det här är för djur.",
  paranuInfoParagraph1Line2: " Är du här för att träffa en partner till ditt djur, en promenadkompis eller en vän till ditt djur? Då har du hittat rätt. Vi är världens bästa djurdatesajt av en viktig anledning. Vi älskar alla djur oavsett ras eller blandras. Alla är lika värda för oss!",
  paranuInfoParagraph1Line3: "Välkommen till Paranu, världens största datingsida för djur, ENBART djur.",
  paranuInfoParagraph1Line4: "Ladda ner appen Paranu till iOS och Android eller besök para.nu på webben.",
  question1:"Hur använder jag Paranu?",
  answer1Line1: "Du kan ladda ner appen Paranu till iOS och Android eller besök para.nu på webben.",
  answer1Line11:"Swipa. Matcha. Chatta. Träffas. Paranu är kul och enkelt. Swipa höger för att gilla någon, swipa vänster för att avstå. Om någon tycker om ditt djur också, är det en matchning! Två djur matchar om båda är intresserade. Bara swipa, matcha och chatta online med dina matchningar, och planera vad som kommer näst!",
  answer1Line2: "Paranu stöder för närvarande iOS 8 och senare, Android 4.4 och senare och de senaste versionerna av alla de vanligaste webbläsarna (Internet Explorer, Chrome, Firefox, Safari, etc.).",
  question2: "Kan jag använda Paranu vart som helst i världen?",
  answer2: "Paranu är en global online datingplattform för djur i över 190 länder.",
  signUpAndGetStarted: "Registrera dig och börja",

  question3: "Hur skapar jag ett Paranu-konto?",
  answer3: "Hämta Paranu-appen för iOS och Android eller besök Para.nu och följ anvisningarna. Det är super lätt.",
  question4: "Kan jag registrera mig utan Facebook?",
  answer4: "Du kan självklart registrera utan Facebook via din e-postadress och telefonnummer.",
  matchingAndMessage:"Matchning och meddelande",
  question5: "Kan jag söka efter en viss person på Paranu?",
  answer5: "Ja, om du vet vem husdjursägaren är, tryck bara på förstoringsglaset och fyll i user ID.",
  question6: "Hur skickar jag ett meddelande till någon?",
  answer6: "Som världens största datingapp för djur kan du chatta med andra lokala djurägare vart än du är. Men endast användare som har angivit samma intressen dig har möjlighet att matcha och chatta med dig. Om du inte har fått en match fortsätter du bara swipa! Det är bara en fråga om tid innan det händer!",
  question7: "Kan jag meddela en användare om vi inte har matchat?",
  answer7: "Nej, för användarnas integritets skull är det inte möjligt att skicka ett meddelande till en användare om inte det har variten match.",
  //question8: "Jag har inte matchat någon, vad ska jag göra?",
 // answer8: "Du kan alltid försöka öka avståndet och fortsätta swiping Det är bara en fråga om tid innan det händer!",
  question9: "Hur rapporterar jag någon?",
  answer10: "Du kan rapportera användare som du anser missbrukar tjänsten, gå till personens profil > tryck på den triangulära ikonen (varningsikonen) > Rapportera.",
  
  
},
ddr:{
  guide:"Häufig gestellte Fragen",
  paranuOverView:"Paranu Ûberblick",
  whatIsParanu:"Was ist Paranu?",
  paranuInfoParagraph1Line1: "Paranu ist die weltweit größte Dating-Seite, um neue Partner für Ihr Tier kennenzulernen. Betrachten Sie uns als eine Dating-Seite für Menschen, aber dies ist für die Tiere.",
  paranuInfoParagraph1Line2: "Bist du hier, um einen Partner für dein Tier zu treffen, einen Gehgefährten, einen Freund für dein Tier? Dann sind Sie bei uns richtig. Wir sind aus einem wichtigen Grund die weltweit beste Dating-Seite für Tiere. Wir lieben alle Tiere unabhängig von Rasse oder Mischling. Jeder ist für uns gleichermaßen wert!",
  paranuInfoParagraph1Line3: "Willkommen auf der weltweit größten Dating-Seite für Tiere NUR Tiere.",
  paranuInfoParagraph1Line4: "Laden Sie die Paranu-App für iOS und Android herunter oder besuchen Sie Para.nu im Internet.",
  question1:"Wie kann ich Paranu verwenden?",
  answer1Line1: "Sie können die Paranu-App für iOS und Android herunterladen oder zu Para.nu wechseln, um Paranu im Internet zu verwenden.",
  answer1Line11:"Fegen. Spiel. Unterhaltun. Treffen. Paranu ist ein Kinderspiel und macht Spaß. Streichen Sie nach rechts, um jemanden zu mögen, streichen Sie nach links, um zu pass. Wenn dich auch jemand mag, ist es ein Spiel! Zwei Tiere stimmen überein, wenn beide interessiert sind. Streichen, passen und chatten Sie online mit Ihren Übereinstimmungen: Lassen Sie dann das Telefon tauchen, Treffen Sie sich im wirklichen Leben und lassen Sie es Liebe sein.",
  answer1Line2: "Paranu unterstützt derzeit iOS 8 und höher, Android 4.4 und höher sowie die neuesten Versionen aller gängigen Browser (Internet Explorer, Chrome, Firefox, Safari usw.).",
  question2: "Kann ich Paranu überall auf der Welt benutzen?",
  answer2: "Paranu ist eine globale Online-Dating-Plattform für Tiere in über 190 Ländern.",
  signUpAndGetStarted: "Melden Sie sich an und legen Sie los",

  question3: "Wie erstelle ich ein Paranu-Konto?",
  answer3: "Laden Sie die Paranu-App für iOS und Android herunter oder besuchen Sie Para.nu. Folgen Sie den Anweisungen. Es ist super einfach.",
  question4: "Kann ich mich ohne Facebook registrieren?",
  answer4: "Sie können sich natürlich auch ohne Facebook über Ihre E-Mail-Adresse und Telefonnummer registrieren.",
  matchingAndMessage:"Matching und Nachrichten",
  question5: "Kann ich bei Paranu nach einer bestimmten Person suchen?",
  answer5: "Ja, wenn Sie wissen, was der Tierbesitzer ist, berühren Sie einfach die Lupe und geben Sie den user ID.",
  question6: "Wie sende ich jemandem eine Nachricht?",
  answer6: "Als weltweit größte Dating-App für Tiere können Sie überall mit anderen Tierbesitzern chatten. Es dürfen jedoch nur Benutzer chatten, die ein gegenseitiges Interesse zueinander haben.Wenn Sie noch keine Spiele erhalten haben, kehren Sie einfach weiter! Es ist nur eine Frage der Zeit bevor es passiert!",
  question7: "Kann ich einem Benutzer eine Nachricht senden, wenn wir nicht übereinstimmen?",
  answer7: "Nein. Aus Gründen des Datenschutzes unserer Benutzer ist es nicht möglich, eine Nachricht an einen Benutzer zu senden, sofern dies nicht der Fall isteine Übereinstimmung.",
  //question8: "Ich habe mit niemandem abgestimmt, was soll ich tun?",
  //answer8: "Sie können immer versuchen, die Entfernung zu vergrößern und dann weiter zu streichen. Es ist nur eine Frage der Zeit, bis es passiert!",
  question9: "Wie kann ich  jemanden anzeigen?",
   answer10: "Sie können Nutzer anzeigen, von denen Sie denken, dass sie sich schlecht benehmen, zum Profil der Person gehen und das Dreieck berühren",
   
   
  },
ru:{
  guide:"Часто задаваемые вопросы",
  paranuOverView:"Обзор Paranu",
  whatIsParanu:"Что такое Paranu?",
  paranuInfoParagraph1Line1: "Paranu - это крупнейший в мире сайт знакомств, чтобы познакомиться с новыми партнерами для вашего животного. Думай о нас как о сайте знакомств для людей, но это для животных. ",
  paranuInfoParagraph1Line2: " Вы здесь, чтобы встретить партнера для вашего животного, приятеля для прогулок или друга для вашего животного? Тогда вы нашли то что вам нужно. Мы лучший в мире сайт знакомств для животных по одной важной причине. Мы любим всех животных независимо от породы или помеси. Все одинаково достойны для нас!",
  paranuInfoParagraph1Line3: "Добро пожаловать на Paranu, крупнейший в мире сайт знакомств для животных, ТОЛЬКО животных.",
  paranuInfoParagraph1Line4: "Загрузите приложение Paranu для iOS и Android или посетите веб-сайт para.nu.",
  question1:"Как я могу использовать Paranu?",
  answer1Line1: "Вы можете скачать приложение Paranu для iOS и Android или перейти на para.nu, чтобы использовать Paranu в Интернете.",
  answer1Line11:"Проводи пальцем. Совпадай. Переписывайся. Встречайся. Paranu это весело и просто. Проведите вправо если вам кто-то понравился, проведите влево чтобы «отказаться». Если кому-нибудь тоже понравилось твоё животное, то это совпадение! Два животных совпадают если оба заинтересованны. Просто проводите пальцем, совпадайте и общайтесь онлайн со своими совпадениями, а затем планируйте, что будет дальше!",
  answer1Line2: "В настоящее время Paranu поддерживает iOS 8 и выше, Android 4.4 и выше и последние версии всех самых распространенных браузеров (Internet Explorer, Chrome, Firefox, Safari и т. Д.).",
  
  question2: "Могу ли я использовать Paranu в любой точке мира?",
  answer2: "Paranu - это глобальная онлайн-платформа знакомств для животных в более чем 190 странах.",
  signUpAndGetStarted: "Зарегистрируйтесь и начните",
  question3: "Как мне создать аккаунт на Paranu?",

  answer3: "Загрузите приложение Paranu для iOS и Android или посетите para.nu и следуйте инструкциям. Это супер просто.",
  question4: "Могу ли я зарегистрироваться без Facebook?",
  answer4: "Конечно, вы можете зарегистрироваться без Facebook через свой адрес электронной почты и номер телефона.",
  matchingAndMessage:"Совпадение и сообщение",
  question5: "Могу ли я найти определенного человека на Paranu?",
  answer5: "Да, если вы знаете, кто владелец домашнего животного, просто коснитесь увеличительного стекла и введите user ID.",
  question6: "Как мне отправить сообщение кому-то?",
  answer6: "Как крупнейшее в мире приложение знакомств для животных, вы можете общаться с другими местными владельцами животных, где бы они ни находились. Только пользователи, которые указали взаимные интересы, имеют возможность совпадать и переписываться. Если вы еще не получили совпадение, просто продолжайте проводить пальцем! Это просто вопрос времени, прежде чем что-то случится!",
  question7: "Могу ли я отправить сообщение пользователю, если мы не соответствовали?",
  answer7: "Нет, ради конфиденциальности наших пользователей, невозможно отправить сообщение пользователю, если не быломатч.",
  //question8: "Я ни с кем не совпал, что мне делать?",
  //answer8: "Вы всегда можете попытаться увеличить расстояние и продолжить движение. Это только вопрос времени, прежде чем это произойдет!",
  question9: "Как мне подать жалобу на кого-нибудь?",
   answer10: "Вы можете пожаловаться на пользователя который по вашему мнению плохо себя ведет, перейдите в профиль этого человека> коснитесь треугольного значка (значок предупреждения)> Пожаловаться.",
   
   
  }
});
export default strings