import PaymentTypeLocalization from 'react-native-localization';

let strings = new PaymentTypeLocalization({
 "en-US":{
   profiles:"Profiles",
   unlimitedProfiles:"Unlimited Profiles",
   standard:"Standard",
   silver:"Silver",
   gold:"Gold",
   submit:"Submit",
   alert1:"please enter your sixteen digit card number",
   alert2:"please enter your card expiry date",
   alert3:"please enter your card three digit cvc number",
   alert4: "Successfully subscribed ,Thank you for your purchase",
   failed:"faild",
   payment: "Payment",
   month: " month",
   youCanCancelAnyTime: "You can cancel any time",
   doYouHaveDiscountCode: "Do you have a discount code?",
   successPlan: "membership.You can now enjoy unlimited swipes and create as many pet profiles your new membership plan allow you to have",
  
   havepromocode: "Have Promo code?",
   submit: "Submit",
   cancel: "Cancel",
   codeisvalidd: "code is valid",
   codeisnotnalidd: "code is not valid",
   months: " months",
   yes: "yes!",

 },
 en:{
  profiles:"Profiles",
  unlimitedProfiles:"Unlimited Profiles",
  standard:"Standard",
  silver:"Silver",
  gold:"Gold",
  submit:"Submit",
   alert1:"please enter your sixteen digit card number",
   alert2:"please enter your card expiry date",
   alert3:"please enter your card three digit cvc number",
   alert4: "Successfully subscribed , Thank you for your purchase",
   failed:"faild",
   payment: "Payment",
   month: " month",
   youCanCancelAnyTime: "You can cancel any time",
   doYouHaveDiscountCode: "Do you have a discount code?",
   successPlan: "membership.You can now enjoy unlimited swipes and create as many pet profiles your new membership plan allow you to have",
 
   havepromocode: "Have Promo code?",
   submit: "Submit",
   cancel: "Cancel", 
   codeisvalidd: "code is valid",
   codeisnotnalidd: "code is not valid",
   months: " months",
   yes: "yes!",
  },
 it: {
  profiles:"Profili",
  unlimitedProfiles:"Profili illimitati",
  standard:"Standard",
  silver:"Argento",
  gold:"Oro",
  submit:"Sottoscrivi",
   alert1:"Per favore inserisci il tuo numero di sedici cifre",
   alert2:"Per favore inserisci la data di scadenza della tua carta",
   alert3:"Per favore inserisci il numero di cvc a tre cifre della tua carta",
   alert4: "Sottoscritto con successo, grazie per il tuo acquisto",
   failed:"Mancato",
   payment: "Pagamento",
   month: " Mese",
   youCanCancelAnyTime: "Puoi annullare qualsiasi momento",
   doYouHaveDiscountCode: "Hai un codice di sconto?",
   successPlan: "membership.You ora puoi godere di swipes illimitati e creare tanti profili di animali domestici che il tuo nuovo piano di abbonamento ti consente di avere",
  
   havepromocode: "Hai un codice promozionale?",
   submit: "Sottoscrivi",
   cancel: "Annulla",
   codeisvalidd: "il codice è valido",
   codeisnotnalidd: "il codice non è valido",
   months: " mesi",
   yes: "sì!",
  },
 fr:{
  profiles:"Profils",
  unlimitedProfiles:"Profils illimités",
  standard:"Standard",
  silver:"Argent",
  gold:"Or",
  submit:"Soumettre",
   alert1:"Veuillez entrer votre numéro de carte à seize chiffres",
   alert2:"Veuillez entrer la date d'expiration de votre carte",
   alert3:"Veuillez entrer votre numéro de cvc à trois chiffres sur votre carte",
   alert4: "Vous vous êtes abonnés avec succès, merci pour votre achat",
   failed:"Échoué",
   payment: "Paiement",
   month: " Mois",
   youCanCancelAnyTime: "Vous pouvez annuler à tout moment",
   doYouHaveDiscountCode: "Avez-vous un code de réduction?",
   successPlan: "adhésion. Vous pouvez maintenant profiter de balayages illimités et créer autant de profils d’animaux que votre nouveau plan d’adhésion vous permet d’avoir.",
   havepromocode: "Avez-code promotionnel?",
   submit: "Soumettre",
   cancel: "Annuler",
   codeisvalidd: "le code est valide",
   codeisnotnalidd: "le code n'est pas valide",
   months: " mois",
   yes: "Oui!",
  },
 es:{
  profiles:"Perfiles",
  unlimitedProfiles:"Perfiles ilimitados",
  standard:"Estándar",
  silver:"Plata",
  gold:"Oro",
  submit:"Enviar",
   alert1:"Por favor ingrese su número de tarjeta de dieciséis dígitos",
   alert2:"Por favor, ingrese la fecha de caducidad de la tarjeta",
   alert3:"Por favor excriba su número de tarjeta de tres dígitos cvc",
   alert4: "Suscrito con éxito, gracias por su compra!",
   failed:"ha fallado",
   payment: "Pago",
   month: " Mes",
   youCanCancelAnyTime: "Puedes cancelar en cualquier momento",
   doYouHaveDiscountCode: "¿Tienes un código de descuento?",
   successPlan: "membresía. Ahora puede disfrutar de swipes ilimitados y crear tantos perfiles de mascotas como su nuevo plan de membresía le permita tener",
   havepromocode: "¿Tienes código promocional?",
   submit: "Enviar",
   cancel: "Cancelar",
   codeisvalidd: "el código es válido",
   codeisnotnalidd: "el código no es válido",
   months: " meses",
   yes: "¡sí!",
  },
 sv:{
  profiles:"Profiler",
  unlimitedProfiles:"Obegränsat antal profiler",
  standard:"Standard",
  silver:"Silver",
  gold:"Guld",
  submit:"Skicka",
   alert1:"Vänligen ange ditt sextonsiffriga kortnummer",
   alert2:"Ange kortets utgångsdatum",
   alert3:"Vänligen ange ditt korts tresiffriga cvc nummer",
   alert4: "Prenumerationen lyckades, tack för ditt köp!",
   failed:"Misslyckdes",
   payment: "Betalning",
   month: " Månad",
   youCanCancelAnyTime: "Du kan avbryta när som helst",
   doYouHaveDiscountCode: "Har du en rabattkod?",
   successPlan: "medlemskap.Du kan nu njuta av obegränsad swipes och skapa så många husdjursprofiler som din nya medlemsplan gör att du kan ha",
   havepromocode: "Har kampanjkod?",
   submit: "Skicka",
   cancel: "Annullera",
   codeisvalidd: "koden är giltig",
   codeisnotnalidd: "koden är inte giltig",
   months: " månader",
   yes: "ja!",
  },
 ddr:{
  profiles:"Profile",
  unlimitedProfiles:"Unbegrenzte Profile",
  standard:"Standard",
  silver:"Silber",
  gold:"Gold",
  submit:"senden",
   alert1:"Bitte geben Sie Ihre 16-ziffrige Kartennummer ein",
   alert2:"Bitte geben Sie das Ablaufdatum Ihrer Karte ein",
   alert3:"Bitte geben SieIhre digit cvc number ein",
   alert4: "Erfolgreich abonniert, vielen Dank für Ihren Einkauf",
   failed:"gescheitert",
   payment: "Zahlung",
   month: " Monat",
   youCanCancelAnyTime: "Sie können jederzeit abbrechen",
   doYouHaveDiscountCode: "Haben Sie einen Gutscheincode?",
   successPlan: "Mitgliedschaft. Sie können jetzt unbegrenzte Wischbewegungen genießen und so viele Tierprofile erstellen, wie es Ihnen Ihr neuer Mitgliedschaftsplan erlaubt",
   havepromocode: "Promo-Code haben",
   submit: "senden",
   cancel: "Stornieren",
   codeisvalidd: "Code ist gültig",
   codeisnotnalidd: "Code ist nicht gültig",
   months: " Monate",
   yes: "Ja!",
  },
 ru:{
  profiles:"Профили",
  unlimitedProfiles:"Неограниченное количество профилей",
  standard:"Стандарт",
  silver:"Серебро",
  gold:"Золото",
  submit:"Отправить",
   alert1:"Пожалуйста, введите шестнадцатизначный номер вашей карты",
   alert2:"Пожалуйста, введите дату истечения срока действия вашей карты",
   alert3:"Пожалуйста, введите трехзначный номер cvc вашей карты",
   alert4: "Успешно подписан, спасибо за покупку!",
   failed:"Не удалось",
   payment: "Оплата",
   month: " Месяц",
   youCanCancelAnyTime: "Вы можете отменить в любое время",
   doYouHaveDiscountCode: "У вас есть код скидки?",
   successPlan: "членство. Теперь вы можете наслаждаться неограниченным количеством просмотров и создавать столько любимых профилей, сколько позволит вам ваш новый план членства.",
   havepromocode: "Есть промо-код?",
   submit: "Отправить",
   cancel: "отменить",
   codeisvalidd: "код действителен",
   codeisnotnalidd: "код недействителен",
   months: " месяцы",
   yes: "да!",
  }
});
export default strings