# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paranu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Paranu
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'Firebase'
 pod 'Firebase/Messaging'






  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'



  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'ParanuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Paranu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Paranu-tvOS

  target 'Paranu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
