import SettingLocalization from 'react-native-localization';

let strings = new SettingLocalization({
 "en-US":{
   instructions:"Instructions",
   distance:"Distance",
   changePassword:"Change Password",
   termsAndConditions:"Terms and Conditions",
   contactUs:"Contact Us",
   internetIssue:"Internet Issue",
   matchingRange:"Matching range",
   updated:"Updated",
   pleaseTypeValidRange:"Please type valid range",
   settings:"Settings",
   introduction:"Introduction",
   logOut:"Log Out",
   upgradeYourMembership:"Upgrade your membership",
   distanceForFindingAMatch:"distance for finding a match from 0-30000 Kilometers (Km)",
   add:"Add",

 },
 en:{
   instructions:"Instructions",
   distance:"Distance",
   changePassword:"Change Password",
   termsAndConditions:"Terms and Conditions",
   contactUs:"Contact Us",
   internetIssue:"Internet Issue",
   matchingRange:"Matching range",
   updated:"Updated",
   pleaseTypeValidRange:"Please type valid range",
   settings:"Settings",
   introduction:"Introduction",
   logOut:"Log Out",
   upgradeYourMembership:"Upgrade your membership",
   distanceForFindingAMatch:"distance for finding a match from 0-30000 Kilometers (Km)",
   add:"Add",
 },
 it: {
  instructions:"Istruzioni",
  distance:"Distanza",
  changePassword:"Cambia la password",
  termsAndConditions:"Termini e condizioni",
  contactUs:"Contattaci",
  internetIssue:"Problema Internet",
  matchingRange:"Distanza di corrispondenza",
  updated:"Aggiornato",
  pleaseTypeValidRange:"Si prega di digitare intervallo valido",
  settings:"Impostazioni",
  introduction:"Introduzione",
  logOut:"Disconnettersi",
  upgradeYourMembership:"Aggiorna la tua iscrizione",
  distanceForFindingAMatch:"Distanza per trovare una corrispondenza da 0-30000 chilometri (Km)",
  add:"Inserisci",
 },
 fr:{
  instructions:"Instructions",
  distance:"Distance",
  changePassword:"Changer le mot de passe",
  termsAndConditions:"Termes et conditions",
  contactUs:"Contactez nous",
  internetIssue:"Problème Internet",
  matchingRange:"Catégorie de matching",
  updated:"Mis à jour",
  pleaseTypeValidRange:"Veuillez saisir une catégorie valide",
  settings:"Réglages",
  introduction:"Introduction",
  logOut:"Se déconnecter",
  upgradeYourMembership:"Mettre à niveau votre abonnement",
  distanceForFindingAMatch:"Distance pour trouver un match de 0 à 30000 kilomètres (km)",
  add:"Ajouter",
  
},
es:{
  instructions:"Instrucciones",
  distance:"Distancia",
  changePassword:"Cambiar contraseña",
  termsAndConditions:"Términos y Condiciones",
  contactUs:"Contáctenos",
  internetIssue:"Problema de internet",
  matchingRange:"Distancia de emparejamientos",
  updated:"Actualizado",
  pleaseTypeValidRange:"Por favor escriba una distancia válida",
  settings:"Ajustes",
  introduction:"Introducción",
  logOut:"Cerrar sesión",
  upgradeYourMembership:"Actualiza tu membresía",
  distanceForFindingAMatch:"Distancia para encontrar pareja de 0 a 30000 kilómetros (km)",
  add:"Añadir",
},
sv:{
  instructions:"Instruktioner",
  distance:"Avstånd",
  changePassword:"Ändra lösenord",
  termsAndConditions:"Användarvillkor",
  contactUs:"Kontakta oss",
  internetIssue:"Nätverksproblem",
  matchingRange:"Avstånd för matcningar",
  updated:"Uppdaterad",
  pleaseTypeValidRange:"Ange ett giltigt avstånd",
  settings:"Inställningar",
  introduction:"Introduktion",
  logOut:"Logga ut",
  upgradeYourMembership:"Uppgradera ditt medlemskap",
  distanceForFindingAMatch:"Avstånd för att hitta en matchning från 0-30000 kilometer (Km)",
  add:"Lägg till",
},
ddr:{
  instructions:"Anleitung",
  distance:"Entfernung",
  changePassword:"Ändere das Passwort",
  termsAndConditions:"Geschäftsbedingungen",
  contactUs:"Kontaktiere uns",
  internetIssue:"Internet-Problem",
  matchingRange:"Entfernung für Ûbereinstimmungen",
  updated:"Aktualisiert",
  pleaseTypeValidRange:"Bitte geben Sie einen gültigen Bereich ein",
  settings:"die Einstellungen",
  introduction:"Einführung",
  logOut:"Abmelden",
  upgradeYourMembership:"Aktualisieren Sie Ihre Mitgliedschaft",
  distanceForFindingAMatch:"Entfernung zum Finden einer Übereinstimmung von 0 bis 30000 Kilometer (Km)",
  add:"hinzufügen",
  
},
ru:{
  instructions:"Инструкции",
  distance:"Расстояние",
  changePassword:"Изменить пароль",
  termsAndConditions:"Условия и положения",
  contactUs:"Связаться с нами",
  internetIssue:"Проблемы с сетью",
  matchingRange:"Расстояние для совпадения",
  updated:"Обновленный",
  pleaseTypeValidRange:"Введите допустимое расстояние",
  settings:"Настройки",
  introduction:"О нас",
  logOut:"Выйти",
  upgradeYourMembership:"Обновите свое членство",
  distanceForFindingAMatch:"Расстояние для нахождения совпадения от 0-30000 километров (км)",
  add:"Добавить",
}
});
export default strings