import ProfileOtherLocalization from 'react-native-localization';

let strings = new ProfileOtherLocalization({
 "en-US":{
  success:"Success",
   alreadyReported: "You have already Reported this user",
   alert1:"Internet issue",
   reporting:"Reporting",
   reportUser:"Report User",
   pet:"Pet",
   changePet:"Change Pet",
   petCertificates:"Pet certificates",
   petVideo:"Pet Video",
   petName:"Pet Name",
   petType:"Pet Type",
   age:"Age",
   birthDate: "Birth Date",
   breed:"Breed",
   size:"Size",
   sex:"Sex",
   city:"City",
   briefInformation:"Brief information",
   lookingFor:"Looking for",
   userProfile:"User Profile",
   otherPet:"Other Pets",

   selectyourpet: "select your pet",
   report: "Report",
   cancel: "Cancel",
   reported: "Reported",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "Months",
    years: "Years",
    interest: "Interest",
    mate: "Mate",
    walk: "Walk",
    meet: "Meet",
    talk: "Talk",
    sit: "Sit",

 },
 en:{
  success:"Success",
  alreadyReported: "You have already Reported this user",
   alert1:"Internet issue",
   reporting:"Reporting",
   reportUser:"Report User",
   pet:"Pet",
   changePet:"Change Pet",
   petCertificates:"Pet certificates",
   petVideo:"Pet Video",
   petName:"Pet Name",
   petType:"Pet Type",
   age:"Age",
   birthDate: "Birth Date",
   breed:"Breed",
   size:"Size",
   sex:"Sex",
   city:"City",
   briefInformation:"Brief information",
   lookingFor:"Looking for",
   userProfile:"User Profile",
   otherPet:"Other Pets",

   selectyourpet: "select your pet",
   report: "Report",
   cancel: "Cancel",
   reported: "Reported",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "Months",
    years: "Years",
    interest: "Interest",
    mate: "Mate",
    walk: "Walk",
    meet: "Meet",
    talk: "Talk",
    sit: "Sit",
 },
 it: {
  success:"Successo",
  alreadyReported: "Hai già segnalato questo utente",
  alert1:"Problema di Internet",
  reporting:"Segnalazione",
  reportUser:"Segnala utente",
  pet:"Animale domestico",
  changePet:"Cambia animale",
  petCertificates:"Certificati dell'animale domestico",
  petVideo:"Pet Video",
  petName:"Nome del cucciolo",
  petType:"Tipo di animale domestico",
  age:"Età",
  birthDate: "Data di nascita",
  breed:"Razza",
  size:"Taglia",
  sex:"Sesso",
  city:"Città",
  briefInformation:"Breve informazione",
  lookingFor:"Cercando",
  userProfile:"Profilo utente",
  otherPet:"Altri animali domestici",

  selectyourpet: "seleziona il tuo animale domestico",
  report: "rapporto",
   cancel: "Annulla",
   reported: "Segnalato",
   bird: "Uccello",
    cat: "Gatto",
    cattle: "Bestiame",
    dog: "Cane",
    fish: "Pesce",
    horse: "Cavallo",
    miniPig: "Mini maiale",
    rabbit: "coniglio",
    rodent: "Roditore",
    reptile: "Rettile",
    other: "Altro",
    crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
    small: "Piccolo",
    medium: "medio",
    big: "Grande",
    dosntMetter: "Non importa",
    male: "Maschio",
    female: "Femmina",
    months: "Mesi",
    years: "Anni",
    interest: "Interesse",
    mate: "Compagno",
    walk: "Camminare",
    meet: "Incontrare",
    talk: "Parlare",
    sit: "Sedersi",
 },
 fr:{
  success:"Succès",
  alreadyReported: "Vous avez déjà signalé cet utilisateur",
  alert1:"Problème Internet",
  reporting:"Rapport",
  reportUser:"Signaler un utilisateur",
  pet:"Animal de compagnie",
  changePet:"Changer d'animal",
  petCertificates:"Certificats d'animaux",
  petVideo:"vidéo pour animaux de compagnie",
  petName:"Nom d'animal domestique",
  petType:"Type d'animal",
  age:"Âge",
  birthDate: "Date de naissance",
  breed:"Race",
  size:"Taille",
  sex:"Sexe",
  city:"Ville",
  briefInformation:"Informations brèves",
  lookingFor:"À la recherche de",
  userProfile:"Profil de l'utilisateur",
  otherPet:"Autres animaux",

  selectyourpet: "sélectionnez votre animal de compagnie",
  report: "rapport",
   cancel: "Annuler",
   reported: "Signalé",
   bird: "Oiseau",
    cat: "Chat",
    cattle: "Bétail",
    dog: "Chien",
    fish: "Poisson",
    horse: "Cheval",
    miniPig: "Miniporc",
    rabbit: "lapin",
    rodent: "Rongeur",
    reptile: "Reptile",
    other: "Autre",
    crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
    small: "Petit",
    medium: "Moyen",
    big: "Grand",
    dosntMetter: "N'a pas d'importance",
    male: "Mâle",
    female: "Femelle",
    months: "Meses",
    years: "Années",
    interest: "Intérêt",
    mate: "Camarade",
    walk: "Marche",
    meet: "Rencontrer",
    talk: "Parler",
    sit: "Asseoir",
},
es:{
  success:"Éxito",
  alreadyReported: "Ya has reportado a este usuario",
  alert1:"Problema de internet",
  reporting:"Reportando",
  reportUser:"Reportar usuario",
  pet:"Mascota",
  changePet:"Cambiar mascota",
  petCertificates:"Certificados de mascotas",
  petVideo:"Video de mascotas",
  petName:"Nombre de mascota",
  petType:"Tipo de mascota",
  age:"Edad",
  birthDate: "Fecha de nacimiento",
  breed:"Raza",
  size:"tamaño",
  sex:"Sexo",
  city:"Ciudad",
  briefInformation:"Breve información",
  lookingFor:"Buscando",
  userProfile:"Perfil del usuario",
  otherPet:"Otras mascotas",

  selectyourpet: "selecciona tu mascota",
  report: "Informe",
   cancel: "Cancelar",
   reported: "Reportado",
   bird: "Pájaro",
    cat: "Gato",
    cattle: "Ganado",
    dog: "Perro",
    fish: "Pez",
    horse: "Caballo",
    miniPig: "Mini cerdo",
    rabbit: "Conejo",
    rodent: "Roedor",
    reptile: "Reptil",
    other: "Otro",
    crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
    small: "Pequeña",
    medium: "Medio",
    big: "Grande",
    dosntMetter: "No importa",
    male: "Masculino",
    female: "Hembra",
    months: "Meses",
    years: "Años",
    interest: "Interes",
    mate: "Compañero",
    walk: "Caminar",
    meet: "Reunirse",
    talk: "Hablar",
    sit: "Sentar",
},
sv:{
  success:"Lyckat",
  alreadyReported: "Du har redan anmält den här användaren",
  alert1:"Nätverksproblem",
  reporting:"Rapporterar",
  reportUser:"Rapportera användare",
  pet:"Husdjur",
  changePet:"Byt husdjur",
  petCertificates:"Husdjurscertifikat",
  petVideo:"Husdjurvideo",
  petName:"Husdjurets namn",
  petType:"Husdjurstyp",
  age:"Ålder",
  birthDate: "Födelsedatum",
  breed:"Ras",
  size:"Storlek",
  sex:"Kön",
  city:"Stad",
  briefInformation:"Kort information",
  lookingFor:"Letar efter",
  userProfile:"Användarprofil",
  otherPet:"Andra husdjur",

  selectyourpet: "välj ditt husdjur",
  report: "Rapportera",
   cancel: "Annullera",
   reported: "Rapporterad",
   bird: "Fågel",
    cat: "Katt",
    cattle: "Boskap",
    dog: "Hund",
    fish: "Fisk",
    horse: "Häst",
    miniPig: "Minigris",
    rabbit: "Kanin",
    rodent: "Gnagare",
    reptile: "Reptil",
    other: "Andra",
    crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
    small: "Liten",
    medium: "Mellan",
    big: "Stor",
    dosntMetter: "Spelar ingen roll",
    male: "Hane",
    female: "Hona",
    months: "Månader",
    years: "år",
    interest: "Intresse",
    mate: "Para",
    walk: "Promenad",
    meet: "Träffa",
    talk: "Prata",
    sit: "Passning",
},
ddr:{
  success:"Erfolgreich",
  alreadyReported: "Du hast diesen Benutzer bereits gemeldet",
  alert1:"Internet-Problem",
  reporting:"Berichterstattung",
  reportUser:"Benutzer melden",
  pet:"Haustier",
  changePet:"Tiere austauchen",
  petCertificates:"Pet-Zertifikate",
  petVideo:"Haustier Video",
  petName:"Haustiername",
  petType:"Haustiertyp",
  age:"Alter",
  birthDate: "Geburtsdatum",
  breed:"Rasse",
  size:"Größe",
  sex:"Sex",
  city:"Stadt",
  briefInformation:"Karten Information",
  lookingFor:"Auf der Suche nach",
  userProfile:"Benutzerprofil",
  otherPet:"Andere Haustiere",

  selectyourpet: "Wählen Sie Ihr Haustier aus",
  report: "Bericht",
   cancel: "Stornieren",
   reported: "Berichtete",
   bird: "Vogel",
    cat: "Katze",
    cattle: "Das Vieh",
    dog: "Hund",
    fish: "Fisch",
    horse: "Pferd",
    miniPig: "Mini Schwein",
    rabbit: "Hase",
    rodent: "Nagetier",
    reptile: "Reptil",
    other: "Andere",
    crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
    small: "Klein",
    medium: "Mittel",
    big: "Groß",
    dosntMetter: "speillt keine Rolle",
    male: "Männlich",
    female: "Weiblich",
    months: "Monate",
    years: "Jahre",
    interest: "Interesse",
    mate: "Kamerad",
    walk: "Gehen",
    meet: "Treffen",
    talk: "Sich unterhalten",
    sit: "Sitzen",
},
ru:{
  success:"Успех",
  alreadyReported: "Вы уже сообщили об этом пользователе",
  alert1:"Проблемы с сетью",
  reporting:"Жалуюсь",
  reportUser:"Пожаловаться на пользователя",
  pet:"домашнее животное",
  changePet:"Изменить питомца",
  petCertificates:"Сертификат домашнего животного",
  petVideo:"Пэт Видео",
  petName:"Имя питомца",
  petType:"Тип питомца",
  age:"Возраст",
  birthDate: "Дата рождения",
  breed:"Порода",
  size:"Размер",
  sex:"Пол",
  city:"Город",
  briefInformation:"Краткая информация",
  lookingFor:"Ищет",
  userProfile:"Профиль пользователя",
  otherPet:"Другие домашние животные",

  selectyourpet: "выберите своего питомца",
  report: "отчет",
   cancel: "отменить",
   reported: "сообщается",
   bird: "Птица",
    cat: "Кошка/Кот",
    cattle: "крупный рогатый скот",
    dog: "Собака",
    fish: "Рыба",
    horse: "Лошадь",
    miniPig: "Мини свинья",
    rabbit: "Кролик",
    rodent: "Грызун",
    reptile: "Рептилия",
    other: "Другие",
    crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
    small: "Маленький",
    medium: "Средний",
    big: "Большой",
    dosntMetter: "Не имеет значения",
    male: "Он",
    female: "Она",
    months: "месяцы",
    years: "лет",
    interest: "Интерес",
    mate: "Приятель",
    walk: "Ходить",
    meet: "Встретить",
    talk: "Говорить",
    sit: "Сидеть",
}
});
export default strings
