import ReportProblemLocalization from 'react-native-localization';

let strings = new ReportProblemLocalization({
 "en-US":{
   name:"Name",
   email:"Email",
   title:"Title",
   issue:"Issue",
   alert2:"Something is Empty",
   report:"Report",
   success:"Success",
   emailSent:"Email Sent",
   emailIsNotValid:"Email is not valid",
   typeYourFullName:"Type your full name",
   typeYourEmail:"Type your email",
   enterYourTitleHere:"Enter subject here",
   enterYourTextHere:"Enter your text here",
   maximum200Characters:"maximum 200 characters",
   sendingMail:"Sending Mail",
   alert1:"Internet issue",
 },
 en:{
   name:"Name",
   email:"Email",
   title:"Title",
   issue:"Issue",
   alert2:"Something is Empty",
   report:"Report",
   success:"Success",
   emailSent:"Email Sent",
   emailIsNotValid:"Email is not valid",
   typeYourFullName:"Type your full name",
   typeYourEmail:"Type your email",
   enterYourTitleHere:"Enter subject here",
   enterYourTextHere:"Enter your text here",
   maximum200Characters:"maximum 200 characters",
   sendingMail:"Sending Mail",
   alert1:"Internet issue",
 },
 it: {
  name:"Nome",
  email:"E-mail",
  title:"Titolo",
  issue:"Problema",
  alert2:"Manca qualcosa",
  report:"Rapporto",
  success:"Successo",
  emailSent:"Email inviata",
  emailIsNotValid:"L'email non è valido",
  typeYourFullName:"Scrivi il tuo nome e congnome",
  typeYourEmail:"Inserisci la tua email",
  enterYourTitleHere:"Inserisci qui il tuo titolo",
  enterYourTextHere:"Inserisci qui il tuo testo",
  maximum200Characters:"Massimo 200 caratteri",
  sendingMail:"Invio di posta",
  alert1:"Problema di Internet",
   
 },
 fr:{
  name:"prénom",
  email:"Email",
  title:"Titre",
  issue:"Problème",
  alert2:"Un champ est manquant",
  report:"Signaler",
  success:"Succès",
  emailSent:"Email envoyé",
  emailIsNotValid:"L'email est non valide",
  typeYourFullName:"Tapez votre nom complet",
  typeYourEmail:"Tapez votre email",
  enterYourTitleHere:"Entrez votre titre ici",
  enterYourTextHere:"Entrez votre texte ici",
  maximum200Characters:"Maximum 200 caractères",
  sendingMail:"Envoi de mail",
  alert1:"Problème Internet",
},
es:{
  name:"Nombre",
  email:"Email",
  title:"Título",
  issue:"Problema",
  alert2:"Algo falta",
  report:"Reportar",
  success:"Éxito",
  emailSent:"Correo electrónico enviado",
  emailIsNotValid:"El correo electrónico no es válido",
  typeYourFullName:"Escriba su nombre completo",
  typeYourEmail:"Escribe tu correo electrónico",
  enterYourTitleHere:"Ingrese su título aquí",
  enterYourTextHere:"Escriba su texto aquí",
  maximum200Characters:"Máximo 200 letras",
  sendingMail:"Enviando correo electrónico",
  alert1:"Problema de internet",

},
sv:{
  name:"Namn",
  email:"E-post",
  title:"Ämne",
  issue:"Problem :",
  alert2:"Något saknas",
  report:"Rapportera",
  success:"Lyckat",
  emailSent:"E-post skickat",
  emailIsNotValid:"Ogiltig e-post",
  typeYourFullName:"Ange ditt fullständiga namn",
  typeYourEmail:"Ange din e-post",
  enterYourTitleHere:"Ange ämne här",
  enterYourTextHere:"Skriv din text här",
  maximum200Characters:"Max 200 tecken",
  sendingMail:"Skickar e-post",
  alert1:"Internetproblem",

},
ddr:{
  name:"Name",
  email:"Email",
  title:"Titel",
  issue:"Problem",
  alert2:"Etwas fehlt",
  report:"Bericht",
  success:"Erfolgreich",
  emailSent:"E-Mail gesendet",
  emailIsNotValid:"Email ist ungültig",
  typeYourFullName:"Geben Sie Ihren vollständigen Namen ein",
  typeYourEmail:"Geben Sie Ihre E-Mail-Adresse ein",
  enterYourTitleHere:"Geben Sie hier Ihren Titel ein",
  enterYourTextHere:"Schreiben SieIhren Text hier ein",
  maximum200Characters:"Maximal 200 Zeichen",
  sendingMail:"Nachrichten senden",
  alert1:"Internet-Problem",
},
ru:{
  name:"название",
  email:"Эл. адрес",
  title:"заглавие",
  issue:"вопрос",
  alert2:"Чего то не хватает",
  report:"Пожаловаться",
  success:"Успешно",
  emailSent:"Письмо отправлено",
  emailIsNotValid:"Эл. Адрес не является действительным",
  typeYourFullName:"Введите свое полное имя",
  typeYourEmail:"Введите адрес электронной почты",
  enterYourTitleHere:"Введите тему здесь",
  enterYourTextHere:"Введите свой текст здесь",
  maximum200Characters:"Максимум 200 символов",
  sendingMail:"Отправка почты",
  alert1:"Проблема интернета",
}
});
export default strings