import IntroductionLocalization from 'react-native-localization';

let strings = new IntroductionLocalization({
 "en-US":{
   text1:"is the world’s largest dating site to meet new partners for your animal. Think of us like a dating site for people, but this is for animals.",
   text2:" you here to meet a partner for your animal, a walk buddy or a friend for your animal? Then you have come to the right place.",
   text3:" Match. Chat. Meet. Paranu is fun and simple. Swipe right to like somebody, swipe left to ‘pass’. If someone like your pet back, it’s a match! Two animals match if both are interested.",
   text4:" to Paranu, the world’s largest dating site for animals, ONLY animals.",
   back:"Back",
   next:"Next",
   letsStart:"Let's Start",
   paranu: "Paranu",
   are: "Are",
   swipe: "Swipe.",
   welcome: "Welcome",
 },
 en:{
  text1:"is the world’s largest dating site to meet new partners for your animal. Think of us like a dating site for people, but this is for animals.",
  text2:" you here to meet a partner for your animal, a walk buddy or a friend for your animal? Then you have come to the right place.",
  text3:" Match. Chat. Meet. Paranu is fun and simple. Swipe right to like somebody, swipe left to ‘pass’. If someone like your pet back, it’s a match! Two animals match if both are interested.",
  text4:" to the Paranu World’s largest dating site for animals, ONLY animals.",
  back:"Back",
  next:"Next",
  letsStart:"Let's Start",
  paranu: "Paranu",
  are: "Are",
   swipe: "Swipe.",
   welcome: "Welcome",
 },
 it: {
  text1:"è il sito di incontri più grande del mondo per incontrare nuovi partner per il tuo animale.Pensate a noi come a un sito di incontri per persone, ma questo è per gli animali.",
  text2:" qui per incontrare un compagno per il tuo animale, un compagno o un amico per il tuo animale? Allora siete venuti nel posto giusto.",
  text3:" Incontro. Chiacchierare. Incontrare. Paranu è divertente e semplice. Scorri verso destra per far piacere a qualcuno, scorri verso sinistra per passare. Se a qualcuno piace il tuo animale domestico, è una corrispondenza! Due animali corrispondono se entrambi sono interessati.",
  text4:" a Paranu, il sito di incontri per animali più grande del mondo, SOLO animali.",
  back:"Indietro",
  next:"Il prossimo",
  letsStart:"Iniziamo",
  paranu: "Paranu",
  are: "Sei",
   swipe: "Spazzata.",
   welcome: "Benvenuto",
 },
 fr:{
  text1:"est le plus grand site de rencontres au monde pour rencontrer de nouveaux partenaires pour votre animal.Une sorte de site de rencontres, mais cette fois-ci pour les animaux.",
  text2:" êtes ici pour rencontrer un partenaire pour les animaux,un compagnon de promenade, un ami pour votre animal? Alors vous êtes au bon endroit.",
  text3:" un Match. Bavarder. Se retrouver. Paranu est simple et amusant. Si quelqu'un aime votre animal en retour, c'est une match!  ",
  text4:" à Paranu, le plus grand site-web de rencontre pour animaux, et UNIQUEMENT les animaux",
  back:"Retour",

  next:"Suivant",
  letsStart:"Commençons",
  paranu: "Paranu",
  are: "Vous",
   swipe: "Chercher",
   welcome: "Bienvenue",
},
es:{
  text1:"es el sitio de citas más grande del mundo para encontrar nuevas parejas para tu animal.Piensa en nosotros como un sitio de citas para personas, pero esto es para animales.",
  text2:" aquí para encontrar un pareja para tu animal, un compañero de paseo o un amigo para tu animal? Entonces has venido al lugar correcto.",
  text3:" Empareja. Charla. Encontrarse. Paranu es divertido y simple. Desliza el dedo hacia la derecha si te gusta alguien, desliza el dedo hacia la izquierda para pasar. Si a alguien le gusta tu mascota de vuelta, es una emparejacion! Dos animales coinciden si ambos están interesados.",
  text4:" a Paranu, el sitio de citas para animales más grande del mundo, SOLO animales.",
  back:"Regresar",

  next:"Siguiente",
  letsStart:"Empecemos",
  paranu: "Paranu",
  are: "¿Estás",
   swipe: "Barrer.",
   welcome: "Bienvenida",
},
sv:{
  text1:"är världens största datingsida för att träffa nya partners för ditt djur. Tänk på oss som en datingsida för människor, men denna är för djur.",
  text2:" du här för att hitta en partner till ditt djur, en promenadvän eller en kompis till ditt djur? Då har du hittat rätt.",
  text3:" Matcha. Chatta. Träffas. Paranu är kul och enkelt. Svep åt höger för att gilla någon, svep vänster för att avstå. On någon gillar ditt husdjur tillbaka, är det en match! Två djur matchar om båda är intresserade.  ",
  text4:" till Paranu, världens största datingsida för djur, ENDAST djur.",
  back:"Tillbaka",

  next:"Nästa",
  letsStart:"Sätt igång",
  paranu: "Paranu",
  are:"Är",
   swipe: "Svep.",
   welcome: "Välkommen",
},
ddr:{
  text1:"ist die weltweit größte Dating-Site, um neue Partner für Ihr Tier kennenzulernen.Betrachten Sie uns als eine Dating-Site für Menschen, aber diese ist für Tiere.",
  text2:" hier, um einen Partner für Ihr Tier, einen Walk Buddy oder einen Freund für Ihr Tier zu treffen? Dann sind Sie bei uns richtig.",
  text3:" Spiel. Plaudern. Treffen. Paranu macht Spaß und ist einfach. Streichen Sie nach rechts, um jemanden zu mögen, streichen Sie nach links, um zu pass Wenn jemand wie dein Haustier zurück, es ist ein Spiel! Zwei Tiere stimmen überein, wenn beide interessiert sind.",
  text4:" zu Paranu, der weltweit größten Datingseite für Tiere, NUR Tiere.",
  back:"zurück",

  next:"Nächste",
  letsStart:"Lass uns beginnen",
  paranu: "Paranu",
  are: "Sie",
   swipe: "Schwung.",
   welcome: "Willkommen",
},
ru:{
  text1:"это крупнейший в мире сайт знакомств, чтобы познакомиться с новыми партнерами для вашего животного. Думайте о нас как о сайте знакомств для людей, но это для животных.",
  text2:" здесь, чтобы встретить партнера для вашего животного, приятеля для прогулок или друга для вашего животного? Тогда вы нашли то что вам нужно.",
  text3:" Совпадай. Переписывайся. Встречайся. Paranu это весело и просто. Проведите вправо если вам кто-то понравился, проведите влево чтобы «отказаться». Если кому-нибудь тоже понравилось твоё животное, то это совпадение! Два животных совпадают, если оба заинтересованны.",
  text4:" пожаловать в Paranu, крупнейший в мире сайт знакомств для животных, ТОЛЬКО животных.",
  back:"Назад",

  next:"Следующий",
  letsStart:"Давайте начнем",
  paranu: "Paranu",
  are: "вы",
   swipe: "красть.",
   welcome: "Добро",
}
});
export default strings