import PetInfoInitialLocalization from 'react-native-localization';

let strings = new PetInfoInitialLocalization({
 "en-US":{
   alert1: "Please fill all fields",
   alert2: "Please select your pet picture",
   alert3: "Please upgrade your account",
   informationAboutYourPet: "Information About Your Pet",
   petName: "Pet Name",
   age: "Age",
   BirthDate: "Birth Date",
   DatePlace: "YYYY-MM-DD",
   petCategory: "Pet Category",
   selectYourPetCategory:"Select your pet's category",
   type: "Type",
   size:"Size",
   selectSizeOfYourPet:"Select size of your pet",
   selectSexOfYourPet:"Select sex of your pet",
   briefInformation:"Brief information",
   tellUsSomethingAboutYourPet:"tell us something about your pet...",
   maximum100Characters: "(Optional maximum 100 characters)",
   next:"Next",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "Months",
    years: "Years",
    selecttypeofyourpet: "Select type of your pet",
    sex: "Sex",
    select: "Select",

 },
 en:{
   alert1: "Please fill all fields",
   alert2: "Please select your pet picture",
   alert3: "Please upgrade your account",
   informationAboutYourPet: "Information About Your Pet",
   petName: "Pet Name",
   age: "Age",
   BirthDate: "Birth Date",
   DatePlace: "YYYY-MM-DD",
   petCategory: "Pet Category",
   selectYourPetCategory:"Select your pet's category",
   type: "Type",
   size:"Size",
   selectSizeOfYourPet:"Select size of your pet",
   selectSexOfYourPet:"Select sex of your pet",
   briefInformation:"Brief information",
   tellUsSomethingAboutYourPet:"tell us something about your pet...",
   maximum100Characters: "(Optional maximum 100 characters)",
   next:"Next",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "months",
    years: "Years",
    selecttypeofyourpet: "Select type of your pet",
    sex: "Sex",
    select: "Select",

 },
 it: {
  alert1: "Per favore riempi tutti i campi",
  alert2: "Si prega di selezionare l'immagine dell'animale domestico",
  alert3: "Si prega di aggiornare il tuo account",
  informationAboutYourPet: "Informazioni sul tuo animale domestico",
  petName: "Nome del cucciolo",
  age: "Età",
  BirthDate: "Data di nascita",
  DatePlace: "AAAA-MM-DD",
  petCategory: "Categoria dell'animale domestico",
  selectYourPetCategory:"Seleziona la categoria del tuo animale domestico",
  type: "Genere",
  size:"Taglia",
  selectSizeOfYourPet:"Seleziona la taglia del tuo animale domestico",
  selectSexOfYourPet:"Seleziona il sesso del tuo animale domestico",
  briefInformation:"Breve informazione",
  tellUsSomethingAboutYourPet:"dicci qualcosa sul tuo animale domestico...",
  maximum100Characters: "(Opzionale massimo 100 caratteri)",
  next:"Il prossimo",
  bird: "Uccello",
    cat: "Gatto",
    cattle: "Bestiame",
    dog: "Cane",
    fish: "Pesce",
    horse: "Cavallo",
    miniPig: "Mini maiale",
    rabbit: "coniglio",
    rodent: "Roditore",
    reptile: "Rettile",
    other: "Altro",
    crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
    small: "Piccolo",
    medium: "medio",
    big: "Grande",
    dosntMetter: "Non importa",
    male: "Maschio",
    female: "Femmina",
    months: "mesi",
    years: "Anni",
    selecttypeofyourpet: "Seleziona il tipo di animale domestico",
    sex: "Sesso",
    select: "Selezionare",

 },
 fr:{
  alert1: "Merci de compléter tous les champs",
  alert2: "Veuillez sélectionner la photo de votre animal",
  alert3: "Veuillez mettre à jour votre compte",
  informationAboutYourPet: "Informations sur votre animal de compagnie",
  petName: "Nom de votre animal de compagnie",
  age: "Âge",
  BirthDate: "Date de naissance",
  DatePlace: "AAAA-MM-JJ",
  petCategory: "Catégorie de votre animal de compagnie",
  selectYourPetCategory:"Sélectionnez la catégorie de votre animal",
  type: "Type",
  size:"Taille",
  selectSizeOfYourPet:"Sélectionnez la taille de votre animal",
  selectSexOfYourPet:"Sélectionnez le sexe de votre animal",
  briefInformation:"Informations brèves",
  tellUsSomethingAboutYourPet:"Parlez-nous de votre animal de compagnie ...",
  maximum100Characters: "(Maximum facultatif 100 caractères)",
  next:"Suivant",
  bird: "Oiseau",
    cat: "Chat",
    cattle: "Bétail",
    dog: "Chien",
    fish: "Poisson",
    horse: "Cheval",
    miniPig: "Miniporc",
    rabbit: "lapin",
    rodent: "Rongeur",
    reptile: "Reptile",
    other: "Autre",
    crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
    small: "Petit",
    medium: "Moyen",
    big: "Grand",
    dosntMetter: "N'a pas d'importance",
    male: "Mâle",
    female: "Femelle",
    months: "meses",
    years: "Années",
    selecttypeofyourpet: "Sélectionnez le type de votre animal",
    sex: "Sexe",
    select: "Sélectionner",

},
es:{
  alert1: "Por favor llene todos los espacios",
  alert2: "Por favor seleccione su foto de mascota",
  alert3: "Por favor actualice su cuenta",
  informationAboutYourPet: "Información sobre su mascota",
  petName: "Nombre de mascota",
  age: "Edad",
  BirthDate: "Fecha de nacimiento",
  DatePlace: "aaaa-mm-dd",
  petCategory: "Categoría de mascota",
  selectYourPetCategory:"Seleccione la categoría de su mascota",
  type: "Tipo",
  size:"Tamaño",
  selectSizeOfYourPet:"Selecciona el tamaño de tu mascota.",
  selectSexOfYourPet:"Selecciona el sexo de tu mascota.",
  briefInformation:"Breve información",
  tellUsSomethingAboutYourPet:"Cuéntanos algo sobre tu mascota ...",
  maximum100Characters: "(Opcional máximo 100 letras)",
  next:"Siguiente",
  bird: "Pájaro",
    cat: "Gato",
    cattle: "Ganado",
    dog: "Perro",
    fish: "Pez",
    horse: "Caballo",
    miniPig: "Mini cerdo",
    rabbit: "Conejo",
    rodent: "Roedor",
    reptile: "Reptil",
    other: "Otro",
    crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
    small: "Pequeña",
    medium: "Medio",
    big: "Grande",
    dosntMetter: "No importa",
    male: "Masculino",
    female: "Hembra",
    months: "meses",
    years: "Años",
    selecttypeofyourpet: "Selecciona el tipo de tu mascota.",
    sex: "Sexo",
    select: "Seleccionar",

},
sv:{
  alert1: "Vänligen fyll i alla fält",
  alert2: "Välj din husdjursbild",
  alert3: "Vänligen uppgradera ditt konto",
  informationAboutYourPet: "Information om ditt husdjur",
  petName: "Husdjurets namn",
  age: "Ålder",
  BirthDate: "Födelsedatum",
  DatePlace: "åååå-mm-dd",
  petCategory: "Husdjurskategori",
  selectYourPetCategory:"Välj ditt husdjurs kategori",
  type: "Typ",
  size:"Storlek",
  selectSizeOfYourPet:"Ange storleken på ditt djur",
  selectSexOfYourPet:"Ange könet på ditt djur",
  briefInformation:"Kort information",
  tellUsSomethingAboutYourPet:"Berätta något om ditt djur…",
  maximum100Characters: "(Valfritt max 100 tecken)",
  next:"Nästa",
  bird: "Fågel",
    cat: "Katt",
    cattle: "Boskap",
    dog: "Hund",
    fish: "Fisk",
    horse: "Häst",
    miniPig: "Minigris",
    rabbit: "Kanin",
    rodent: "Gnagare",
    reptile: "Reptil",
    other: "Andra",
    crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
    small: "Liten",
    medium: "Mellan",
    big: "Stor",
    dosntMetter: "Spelar ingen roll",
    male: "Hane",
    female: "Hona",
    months: "månader",
    years: "år",
    selecttypeofyourpet: "Välj typ av ditt husdjur",
    sex: "Kön",
    select: "Välj",

},
ddr:{
  alert1: "Bitte alle Felder ausfüllen",
  alert2: "Bitte wählen Sie Ihr Haustierbild aus",
  alert3: "Bitte aktualisieren Sie Ihr Konto",
  informationAboutYourPet: "Informationen zu Ihrem Haustier",
  petName: "Haustiername",
  age: "Alter",
  BirthDate: "Geburtsdatum",
  DatePlace: "JJJJ-MM-TT",
  petCategory: "Haustierkategorie",
  selectYourPetCategory:"Wählen Sie die Kategorie Ihres Haustieres aus",
  type: "Art",
  size:"Größe",
  selectSizeOfYourPet:"Wählen Sie die Größe Ihres Haustieres",
  selectSexOfYourPet:"Wählen Sie das Geschlecht Ihres Haustieres aus",
  briefInformation:"Karten Information",
  tellUsSomethingAboutYourPet:"Erzählen Sie uns etwas über Ihren Haustier ...",
  maximum100Characters: "(Optional maximal 100 Zeichen)",
  next:"Nächste",
  bird: "Vogel",
    cat: "Katze",
    cattle: "Das Vieh",
    dog: "Hund",
    fish: "Fisch",
    horse: "Pferd",
    miniPig: "Mini Schwein",
    rabbit: "Hase",
    rodent: "Nagetier",
    reptile: "Reptil",
    other: "Andere",
    crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
    small: "Klein",
    medium: "Mittel",
    big: "Groß",
    dosntMetter: "speillt keine Rolle",
    male: "Männlich",
    female: "Weiblich",
    months: "Monate",
    years: "Jahre",
    selecttypeofyourpet: "Wählen Sie den Typ Ihres Haustieres",
    sex: "Sex",
    select: "Wählen",

},
ru:{
  alert1: "Пожалуйста заполните все поля",
  alert2: "Пожалуйста, выберите вашу фотографию питомца",
  alert3: "Пожалуйста, обновите свой аккаунт",
  informationAboutYourPet: "Информация о вашем питомце",
  petName: "Имя питомца",
  age: "Возраст",
  BirthDate: "Дата рождения",
  DatePlace: "гггг-мм-дд",
  petCategory: "Категория домашних животных",
  selectYourPetCategory:"Выберите категорию вашего питомца",
  type: "Тип",
  size:"Размер",
  selectSizeOfYourPet:"Выберите размер вашего питомца",
  selectSexOfYourPet:"Выберите пол вашего питомца",
  briefInformation:"Краткая информация",
  tellUsSomethingAboutYourPet:"Расскажите нам что-нибудь о своем питомце ...",
  maximum100Characters: "(Максимум 100 символов)",
  next:"Следующий",
  bird: "Птица",
    cat: "Кошка/Кот",
    cattle: "крупный рогатый скот",
    dog: "Собака",
    fish: "Рыба",
    horse: "Лошадь",
    miniPig: "Мини свинья",
    rabbit: "Кролик",
    rodent: "Грызун",
    reptile: "Рептилия",
    other: "Другие",
    crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
    small: "Маленький",
    medium: "Средний",
    big: "Большой",
    dosntMetter: "Не имеет значения",
    male: "Он",
    female: "Она",
    months: "месяцы",
    years: "лет",
    selecttypeofyourpet: "Выберите тип вашего питомца",
    sex: "Пол",
    select: "Выбрать",

}
});
export default strings
