import ProfileLocalization from 'react-native-localization';

let strings = new ProfileLocalization({
 "en-US":{
   internetIssue:"Internet issue",
   profile:"Profile",
   userNumber:"User number",
   pet:"Pet",
   changePet:"Change Pet",
   petCertificate:"Pet certificates",
   petVideo:"Pet Video",
   petName:"Pet Name",
   petType:"Pet Type",
   briefInformation:"Brief information",
   petType:"Pet Type",
   lookingFor:"Looking for",
   breed:"Breed",
   city:"City",
   sex:"Sex",
   size:"Size",
   age:"Age",
   birthDate:"Birth Date",
   addInterest:"Add interest",
   addPet:"Add Pet",

   otherPet:"Other Pets",
   edit: "Edit",
   upgradeaccount: "Please upgrade your account",
   upgrade: "Upgrade",
   cancel: "Cancel",

   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "Months",
    years: "Years",
    userid: "User ID",

 },
 en:{
  internetIssue:"Internet issue",
  profile:"Profile",
  userNumber:"User number",
  pet:"Pet",
  changePet:"Change Pet",
  petCertificate:"Pet certificates",
  petVideo:"Pet Video",
  petName:"Pet Name",
  petType:"Pet Type",
  briefInformation:"Brief information",
  petType:"Pet Type",
  lookingFor:"Looking for",
  breed:"Breed",
  city:"City",
  sex:"Sex",
  size:"Size",
  age:"Age",
  birthDate:"Birth Date",
  addInterest:"Add Interest",
  addPet:"Add Pet",

  otherPet:"Other Pets",
  edit: "Edit",
  upgradeaccount: "Please upgrade your account",
   upgrade: "Upgrade",
   cancel: "Cancel",
   bird: "Bird",
    cat: "Cat",
    cattle: "Cattle",
    dog: "Dog",
    fish: "Fish",
    horse: "Horse",
    miniPig: "Mini pig",
    rabbit: "Rabbit",
    rodent: "Rodent",
    reptile: "Reptile",
    other: "Other",
    crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    small: "Small",
    medium: "Medium",
    big: "Big",
    dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    months: "Months",
    years: "Years",
    userid: "User ID",
 },
 it: {
  internetIssue:"Problema di Internet",
  profile:"Profilo",
  userNumber:"Numero dell'utente",
  pet:"Animale domestico",
  changePet:"Cambia Pet",
  petCertificate:"Certificati dell'animale domestico",
  petVideo:"Pet Video",
  petName:"Nome dell`animale",
  petType:"Tipo di animale domestico",
  briefInformation:"Breve informazione",
  petType:"Tipo di animale domestico",
  lookingFor:"Cercando",
  breed:"Razza",
  city:"Città",
  sex:"Sesso",
  size:"Taglia",
  age:"Età",
  birthDate: "Data di nascita",
  addInterest:"Aggiungi interesse",
  addPet:"Aggiungi animale domestico",

  otherPet:"Altri animali domestici",
  edit: "modificare",
  upgradeaccount: "Si prega di aggiornare il tuo account",
   upgrade: "Aggiornamento",
   cancel: "Annulla",
   bird: "Uccello",
    cat: "Gatto",
    cattle: "Bestiame",
    dog: "Cane",
    fish: "Pesce",
    horse: "Cavallo",
    miniPig: "Mini maiale",
    rabbit: "coniglio",
    rodent: "Roditore",
    reptile: "Rettile",
    other: "Altro",
    crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
    small: "Piccolo",
    medium: "medio",
    big: "Grande",
    dosntMetter: "Non importa",
    male: "Maschio",
    female: "Femmina",
    months: "Mesi",
    years: "Anni",
    userid: "ID utente",
 },
 fr:{
  internetIssue:"Problème Internet",
  profile:"Profil",
  userNumber:"Numéro d'utilisateur",
  pet:"Animal de compagnie",
  changePet:"Changer d'animal",
  petCertificate:"Certificats d'animaux",
  petVideo:"vidéo pour animaux de compagnie",
  petName:"Nom d'animal domestique",
  petType:"Type d'animal",
  briefInformation:"Informations brèves",
  petType:"Type d'animal",
  lookingFor:"À la recherche de",
  breed:"Race",
  city:"Ville",
  sex:"Sexe",
  size:"Taille",
  age:"Âge",
  birthDate: "Date de naissance",
  addInterest:"Ajouter un intérêt",
  addPet:"Ajouter un animal",

  otherPet:"Autres animaux",
  edit: "modifier",
  upgradeaccount: "Veuillez mettre à jour votre compte",
   upgrade: "Améliorer",
   cancel: "Annuler",
   bird: "Oiseau",
    cat: "Chat",
    cattle: "Bétail",
    dog: "Chien",
    fish: "Poisson",
    horse: "Cheval",
    miniPig: "Miniporc",
    rabbit: "lapin",
    rodent: "Rongeur",
    reptile: "Reptile",
    other: "Autre",
    crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
    small: "Petit",
    medium: "Moyen",
    big: "Grand",
    dosntMetter: "N'a pas d'importance",
    male: "Mâle",
    female: "Femelle",
    months: "Meses",
    years: "Années",
    userid: "ID utilisateur",
 },
 es:{
  internetIssue:"Problema de internet",
  profile:"Perfil",
  userNumber:"Numero de usuario",
  pet:"Mascota",
  changePet:"Cambiar mascota",
  petCertificate:"Certificados de mascotas",
  petVideo:"Video de mascotas",
  petName:"Nombre de mascota",
  petType:"Tipo de mascota",
  briefInformation:"Breve información",
  petType:"Tipo de mascota",
  lookingFor:"Buscando",
  breed:"Raza",
  city:"Ciudad",
  sex:"Sexo",
  size:"tamaño",
  age:"Edad",
  birthDate: "Fecha de nacimiento",
  addInterest:"Agregar interes",
  addPet:"Añadir mascota",

  otherPet:"Otras mascotas",
  edit: "Editar",
  upgradeaccount: "Por favor actualice su cuenta",
   upgrade: "Mejorar",
   cancel: "Cancelar",
   bird: "Pájaro",
    cat: "Gato",
    cattle: "Ganado",
    dog: "Perro",
    fish: "Pez",
    horse: "Caballo",
    miniPig: "Mini cerdo",
    rabbit: "Conejo",
    rodent: "Roedor",
    reptile: "Reptil",
    other: "Otro",
    crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
    small: "Pequeña",
    medium: "Medio",
    big: "Grande",
    dosntMetter: "No importa",
    male: "Masculino",
    female: "Hembra",
    months: "Meses",
    years: "Años",
    userid: "ID de usuario",
 },
 sv:{
  internetIssue:"Nätverksproblem",
  profile:"Profil",
  userNumber:"Användarnummer",
  pet:"Husdjur",
  changePet:"Byt husdjur",
  petCertificate:"Husdjurscertifikat",
  petVideo:"Husdjurvideo",
  petName:"Husdjurets namn",
  petType:"Husdjurstyp",
  briefInformation:"Kort information",
  petType:"Husdjurstyp",
  lookingFor:"Söker efter",
  breed:"Ras",
  city:"Stad",
  sex:"Kön",
  size:"Storlek",
  age:"Ålder",
  birthDate: "Födelsedatum",
  addInterest:"Lägg till intresse",
  addPet:"Lägg till husdjur",

  otherPet:"Andra husdjur",
  edit: "Redigera",
  upgradeaccount: "Uppgradera ditt konto",
   upgrade: "Uppgradering",
   cancel: "Annullera",
   bird: "Fågel",
    cat: "Katt",
    cattle: "Boskap",
    dog: "Hund",
    fish: "Fisk",
    horse: "Häst",
    miniPig: "Minigris",
    rabbit: "Kanin",
    rodent: "Gnagare",
    reptile: "Reptil",
    other: "Andra",
    crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
    small: "Liten",
    medium: "Mellan",
    big: "Stor",
    dosntMetter: "Spelar ingen roll",
    male: "Hane",
    female: "Hona",
    months: "Månader",
    years: "år",
    userid: "Användar-ID",
 },
 ddr:{
  internetIssue:"Internet-Problem",
  profile:"Profil",
  userNumber:"Benutzernummer",
  pet:"Haustier",
  changePet:"Haustier austauchen ",
  petCertificate:"Pet-Zertifikate",
  petVideo:"Haustier Video",
  petName:"Haustiername",
  petType:"Haustiertyp",
  briefInformation:"Karten Information",
  petType:"Haustiertyp",
  lookingFor:"Auf der Suche nach",
  breed:"Rasse",
  city:"Stadt",
  sex:"Sex",
  size:"Größe",
  age:"Alter",
  birthDate: "Geburtsdatum",
  addInterest:"Interesse hinzufügen",
  addPet:"Haustier hinzufügen",

  otherPet:"Andere Haustiere",
  edit: "Bearbeiten",
  upgradeaccount: "Bitte aktualisieren Sie Ihr Konto",
   upgrade: "Aktualisierung",
   cancel: "Stornieren",
   bird: "Vogel",
    cat: "Katze",
    cattle: "Das Vieh",
    dog: "Hund",
    fish: "Fisch",
    horse: "Pferd",
    miniPig: "Mini Schwein",
    rabbit: "Hase",
    rodent: "Nagetier",
    reptile: "Reptil",
    other: "Andere",
    crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
    small: "Klein",
    medium: "Mittel",
    big: "Groß",
    dosntMetter: "speillt keine Rolle",
    male: "Männlich",
    female: "Weiblich",
    months: "Monate",
    years: "Jahre",
    userid: "Benutzer-ID",
 },
 ru:{
  internetIssue:"Проблемы с сетью",
  profile:"Профиль",
  userNumber:"Номер пользователя",
  pet:"Домашнее животное",
  changePet:"Изменить питомца",
  petCertificate:"Сертификат домашнего животного",
  petVideo:"Пэт Видео",
  petName:"Имя питомца",
  petType:"Тип питомца",
  briefInformation:"Краткая информация",
  petType:"Тип питомца",
  lookingFor:"Ищет",
  breed:"Порода",
  city:"Город",
  sex:"Пол",
  size:"Размер",
  age:"Возраст",
  birthDate: "Дата рождения",
  addInterest:"Добавить интерес",
  addPet:"Добавить питомца",

  otherPet:"Другие домашние животные",
  edit: "редактировать",
  upgradeaccount: "Пожалуйста, обновите свой аккаунт",
   upgrade: "Обновить",
   cancel: "отменить",
   bird: "Птица",
    cat: "Кошка/Кот",
    cattle: "крупный рогатый скот",
    dog: "Собака",
    fish: "Рыба",
    horse: "Лошадь",
    miniPig: "Мини свинья",
    rabbit: "Кролик",
    rodent: "Грызун",
    reptile: "Рептилия",
    other: "Другие",
    crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
    small: "Маленький",
    medium: "Средний",
    big: "Большой",
    dosntMetter: "Не имеет значения",
    male: "Он",
    female: "Она",
    months: "месяцы",
    years: "лет",
    userid: "Идентификатор пользователя",
 }
});
export default strings
