import MatchingLocalization from 'react-native-localization';

let strings = new MatchingLocalization({
 "en-US":{
   alert1:"Internet issue",
   matchings:"Matchings",
   matched:"Matched",
   noMatchingYetSwipeToGetSome:"No matchings yet, swipe to get some.",
   name:"Name",
   sex:"Sex",
   interest: "Interest",
   type: "Type",
   closestCity: "Closest City",
   profile:"Profile",
   message: "Message",
   back:"Back",
   itsamatchnawww: "It's a match. Nawwww",
   sendmessage: "Send Message",
   continueswipping:"Continue Swiping",
   dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
   sit: "Sit",
   crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",

 },
 en:{
  alert1:"Internet issue",
  matchings:"Matchings",
   matched:"Matched",
   noMatchingYetSwipeToGetSome:"No matchings yet, swipe to get some.",
   name:"Name",
   sex:"Sex",
   interest: "Interest",
   type: "Type",
   closestCity: "Closest City",
   profile:"Profile",
   message: "Message",
   back:"Back",

   itsamatchnawww: "It's a match. Nawwww",
   sendmessage: "Send Message",
   continueswipping:"Continue Swiping",
   dosntMetter: "Doesn't matter",
    male: "Male",
    female: "Female",
    mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
   sit: "Sit",
   crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
 },
 it: {
  alert1:"Problema di Internet",
  matchings:"Correspondono le forme",
   matched:"Corresponde la forrma",
   noMatchingYetSwipeToGetSome:"Nessuna corrispondenza ancora, scorrere sul telefono per ottenere un pò",
   name:"Nome",
   sex:"Sesso",
   interest: "Interesse",
   type: "Tipo",
   closestCity: "La città più vicina",
   profile:"Profilo",
   message: "Messaggio",
   back:"Indietro",

   itsamatchnawww: "È una partita. Nawwww",
   sendmessage: "Invia messaggio",
   continueswipping:"Continua a scorrere",
   dosntMetter: "Non importa",
   male: "Maschio",
   female: "Femmina",
    mate: "Compagno",
   walk: "Camminare",
   meet: "Incontrare",
   talk: "Parlare",
   sit: "Sedersi",
   crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
 },
 fr:{
  alert1:"Problème Internet",
  matchings:"Vos Matchs",
   matched:"Matché",
   noMatchingYetSwipeToGetSome:"Aucun Match pour le moment, swipez pour un nouveau match.",
   name:"prénom",
   sex:"Sexe",
   interest: "Intérêt",
   type: "Type",
   closestCity: "La ville la plus proche",
   profile:"Profil",
   message: "Message",
   back:"Retour",

   itsamatchnawww: "C'est un match. Nawwww",
   sendmessage: "Envoyer le message",
   continueswipping:"Continuer à glisser",
   dosntMetter: "N'a pas d'importance",
   male: "Mâle",
   female: "Femelle",
    mate: "Camarade",
   walk: "Marche",
   meet: "Rencontrer",
   talk: "Parler",
   sit: "Asseoir",
   crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
 },
 es:{
  alert1:"Problema de internet",
  matchings:"Emparejamientos",
   matched:"Emparejado",
   noMatchingYetSwipeToGetSome:"Aún no hay emparejaciones, desliza para obtener algunas.",
   name:"Nombre",
   sex:"Sexo",
   interest: "Interes",
   type: "Tipo",
   closestCity: "Ciudad más cercana",
   profile:"Perfil",
   message: "Mensaje",
   back:"Espalda",

   itsamatchnawww: "Es un partido. Nawwww",
   sendmessage: "Enviar mensaje",
   continueswipping:"Continuar deslizando",
   dosntMetter: "No importa",
   male: "Masculino",
   female: "Hembra",
    mate: "Compañero",
   walk: "Caminar",
   meet: "Reunirse",
   talk: "Hablar",
   sit: "Sentar",
   crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
 },
 sv:{
  alert1:"Nätverksproblem",
  matchings:"Matchningar",
   matched:"Matchade",
   noMatchingYetSwipeToGetSome:"Inga matchningar ännu, svep för att få några.",
   name:"Namn",
   sex:"Kön",
   interest: "Intresse",
   type: "Typ",
   closestCity: "Närmsta stad",
   profile:"Profil",
   message: "Meddelande",
   back:"Tillbaka",

   itsamatchnawww: "Du har en matchning. Nawwww",
   sendmessage: "Skicka meddelande",
   continueswipping:"Fortsätt Svajpa",
   dosntMetter: "Spelar ingen roll",
   male: "Hane",
    female: "Hona",
   mate: "Para",
   walk: "Promenad",
   meet: "Träffa",
   talk: "Prata",
   sit: "Passning",
   crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
 },
 ddr:{
  alert1:"Internet-Problem",
  matchings:"Übereinstimmungen",
   matched:"Abgestimmt",
   noMatchingYetSwipeToGetSome:"Noch keine Übereinstimmungen, streichen, um welche zu bekommen.",
   name:"Name",
   sex:"Sex",
   interest: "Interesse",
   type: "Art",
   closestCity: "Nächstgelegene Stadt",
   profile:"Profil",
   message: "Nachricht",
   back:"Zurück",

   itsamatchnawww: "Es ist ein Spiel. Nawwww",
   sendmessage: "Nachricht senden",
   continueswipping:"Wischen Sie weiter",
   dosntMetter: "Macht nichts",
   male: "Männlich",
    female: "Weiblich",
   mate: "Kamerad",
   walk: "Gehen",
   meet: "Treffen",
   talk: "Sich unterhalten",
   sit: "Sitzen",
   crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
 },
 ru:{
  alert1:"Проблемы с сетью",
  matchings:"Совпадения",
   matched:"Совпало",
   noMatchingYetSwipeToGetSome:"Совпадений пока нет, проведите пальцем, чтобы получить.",
   name:"Има",
   sex:"Пол",
   interest: "Интерес",
   type: "Тип",
   closestCity: "Ближайший город",
   profile:"Профиль",
   message: "Сообщение",
   back:"назад",

   itsamatchnawww: "Это матч. Nawwww",
   sendmessage: "Отправить сообщение",
   continueswipping:"Продолжить смахивание",
   dosntMetter: "Не имеет значения",
   male: "Он",
   female: "Она",
    mate: "Приятель",
   walk: "Ходить",
   meet: "Встретить",
   talk: "Говорить",
   sit: "Сидеть",
   crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
 }
});
export default strings
