 
import ChangePasswordLocalization from 'react-native-localization';

let strings = new ChangePasswordLocalization({
 "en-US":{
   changePassword:"Change Password",
   oldPassword:"Old Password",
   newPassword:"New Password",
   confirmPassword:"Confirm Password",
   forgetPassword: "Forget Password",
   alert1:"Password should be more then eight characters",
   alert2:"Password successfully changed",
   alert3:"New password is not matching",
   changingPassword:"Changing password",
   ok: "OK",

 },
 en:{
    changePassword:"Change Password",
    oldPassword:"Old Password",
    newPassword:"New Password",
    confirmPassword:"Confirm Password",
    forgetPassword: "Forget Password",
    alert1:"Password should be more then eight characters",
   alert2:"Password successfully changed",
   alert3:"New password is not matching",
   changingPassword:"Changing password",
   ok: "OK",
 },
 it: {
    changePassword:"Cambia la password",
    oldPassword:"vecchia password",
    newPassword:"Nuova password",
    confirmPassword:"conferma password",
    forgetPassword: "dimenticare la password",
    alert1:"La password dovrebbe essere più di otto caratteri",
   alert2:"Password cambiata, successo",
   alert3:"La nuova password non corrisponde",
   changingPassword:"Modifica della password",
   ok: "ok",
 },
 fr:{
   changePassword:"Changer le mot de passe",
   oldPassword:"ancien mot de passe",
   newPassword:"Nouveau mot de passe",
   confirmPassword:"Confirmez le mot de passe",
   forgetPassword: "Mot de passe oublié",
   alert1:"Le mot de passe doit comporter plus de huit caractères.",
   alert2:"Mot de passe changé avec succès",
   alert3:"Le nouveau mot de passe ne correspond pas",
   changingPassword:"Changement du mot de passe",
   ok: "D'accord",
},
es:{
   changePassword:"Cambia la contraseña",
   oldPassword:"Contraseña anterior",
   newPassword:"Nueva contraseña",
   confirmPassword:"Confirmar contraseña",
   forgetPassword: "Contraseña olvidada",
   alert1:"La contraseña debe tener más de ocho caracteres.",
   alert2:"Contraseña cambiada, éxito",
   alert3:"La nueva contraseña no coincide",
   changingPassword:"Cambio de contraseña",
   ok: "DE ACUERDO",
},
sv:{
   changePassword:"Ändra lösenord",
   oldPassword:"Gammalt lösenord",
   newPassword:"Nytt lösenord",
   confirmPassword:"Bekräfta lösenord",
   forgetPassword: "Glömt lösenord",
   alert1:"Lösenordet måste vara minst 8 tecken",
   alert2:"Lösenordet ändrat",
   alert3:"Det nya lösenordet matchar inte",
   changingPassword:"Ändrar lösenord",
   ok: "ok",
},
ddr:{
   changePassword:"Ändere das Passwort",
   oldPassword:"Altes Passwort",
   newPassword:"Neues Kennwort",
   confirmPassword:"Passwort bestätigen",
   forgetPassword: "Passwort vergessen", 
   alert1:"Das Passwort sollte aus mehr als acht Zeichen bestehen",
   alert2:"Passwort geändert, Erfolg",
   alert3:"Neues Passwort stimmt nicht überein",
   changingPassword:"Passwort ändern",
   ok: "OK",
},
ru:{
   changePassword:"Изменить пароль",
   oldPassword:"Старый пароль",
   newPassword:"новый пароль",
   confirmPassword:"Подтвердите Пароль",
   forgetPassword: "Забыл пароль",
   alert1:"Пароль должен содержать минимум восемь символов",
   alert2:"Пароль изменён",
   alert3:"Новый пароль не совпадает",
   changingPassword:"Смена пароля",
   ok: "Хорошо",
},
});

export default strings


