 import HomeLocalization from 'react-native-localization';

let strings = new HomeLocalization({
 "en-US":{
      name: "Name:",
      sex: "Sex :",
      interest: "Interest :",
      type: "Type :",
      closestCity: "Closest City :",
      thereIsNoDataToShowAccordingYourInterest: "There is no data to show , according to your preferences.\n Try to change the distance.",
      alert1: "Internet Issue",
      title: "Title:",
      like: "LIKE",
      nope: "NOPE",
      search: "Search",
      cancel: "Cancel",
      loading: "Loading",

      home: "Home",
   itsamatchnawww: "It's a match. Nawwww",
   sendmessage: "Send Message",
   continueswipping:"Continue Swiping",
   pleasewat: "Please wait",
   mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
   sit: "Sit",
   crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    male: "Male",
    female: "Female",
    ownerprofile: "Owner's Profile",

   },

     en: {
         name: "Name :",
         sex: "Sex :",
         interest: "Interest :",
         type: "Type :",
         closestCity: "Closest City :",
         thereIsNoDataToShowAccordingYourInterest: "There is no data to show , according to your preferences.\n Try to increase the distance ",
         alert1: "Internet Issue",
         title: "Title:",
         like: " LIKE",
         nope: "NOPE",
         search: "search",
         cancel: "Cancel",
         loading: "Loading",
         home: "Home",

   itsamatchnawww: "It's a match. Nawwww",
   sendmessage: "Send Message",
   continueswipping:"Continue Swiping",
   pleasewat: "Please wait",
   mate: "Mate",
   walk: "Walk",
   meet: "Meet",
   talk: "Talk",
   sit: "Sit",
   crossBreed: "Crossbreed",
    pureBreed: "Purebred",
    dontKnow: "Don't Know",
    male: "Male",
    female: "Female",
    ownerprofile: "Owner's Profile",
      },

      it: {
            name: "Nome",
            sex: "Sesso",
            interest: "Interesse",
            type: "Genere",
            closestCity: "La città più vicina",
            thereIsNoDataToShowAccordingYourInterest: "Non ci sono dati da mostrare, secondo il vostro interesse.\n Prova a cambiare la distanza.",
            alert1: "Problema Internet",
            title: "Titolo",
            like: "PIACE",
            nope: "NO",
            search: "Ricerca",
            cancel: "Annulla",
            loading: "Caricamento in corso",

            home: "Casa",
            itsamatchnawww: "È una partita. Nawwww",
   sendmessage: "Invia messaggio",
   continueswipping:"Continua a scorrere",
   pleasewat: "attendere prego",
   mate: "Compagno",
   walk: "Camminare",
   meet: "Incontrare",
   talk: "Parlare",
   sit: "Sedersi",
   crossBreed: "Incrocio",
    pureBreed: "Di razza",
    dontKnow: "Non so",
    male: "Maschio",
    female: "Femmina",
    ownerprofile: "Profilo del proprietario",
         },
      fr: {
            name: "prénom :",
            sex: " Sexe :",
            interest: "Intérêt :",
            type: "Type :",
            closestCity: "La ville la plus proche :",
            thereIsNoDataToShowAccordingYourInterest: "Il n'y a pas de données à afficher, selon votre intérêt.\n Essayez de changer la distance.",
            alert1: "Problème Internet",
            title: "Titre",
            like: "AIMER",
            nope: "NAN",
            search: "Rechercher",
            cancel: "Annuler",
            loading: "Chargement",
            home: "Accueil",
            itsamatchnawww: "C'est un match. Nawwww",
   sendmessage: "Envoyer le message",
   continueswipping:"Continuer à glisser",
   pleasewat: "S'il vous plaît, attendez",
   mate: "Camarade",
   walk: "Marche",
   meet: "Rencontrer",
   talk: "Parler",
   sit: "Asseoir",
   crossBreed: "Race croisée",
    pureBreed: "Race pure",
    dontKnow: "Je ne sais pas",
    male: "Mâle",
    female: "Femelle",
    ownerprofile: "Profil du propriétaire",
         },
         es: {
            name: "Nombre :",
            sex: " Sexo :",
            interest: "Interes :",
            type: "Tipo :",
            closestCity: "Ciudad más cercana",
            thereIsNoDataToShowAccordingYourInterest: "No hay datos para mostrar, según su preferencia.\n Intenta cambiar la distancia.",
            alert1: "Problema de internet",
            title: "Título",
            like: "ME GUSTA",
            nope: "NO",
            search: "Buscar",
            cancel: "Cancelar",
            loading: "Cargando",

            home: "Casa",
            itsamatchnawww: "Es un partido. Nawwww",
   sendmessage: "Enviar mensaje",
   continueswipping:"Continuar deslizando",
   pleasewat: "por favor espera",
   mate: "Compañero",
   walk: "Caminar",
   meet: "Reunirse",
   talk: "Hablar",
   sit: "Sentar",
   crossBreed: "Híbrido",
    pureBreed: "De pura raza",
    dontKnow: "No se",
    male: "Masculino",
    female: "Hembra",
    ownerprofile: "Perfil del propietario",
         },
         sv: {
            name: "Namn :",
            sex: " Kön :",
            interest: "Intresse :",
            type: "Typ  :",
            closestCity: "Närmaste stad :",
            thereIsNoDataToShowAccordingYourInterest: "Det finns inga uppgifter att visa enligt dina önskemål.\n Pröva att ändra avståndet.",
            alert1: "Nätverksproblem",
            title: "Titel",
            like: "GILLAR",
            nope: "NEJ",
            search: "Sök",
            cancel: "Avbryt",
            loading: "Läser in",

            home: "Hem",
            itsamatchnawww: "Du har en matchning. Nawwww",
   sendmessage: "Skicka meddelande",
   continueswipping:"Fortsätt Svajpa",
   pleasewat: "Letar",
   mate: "Para",
   walk: "Promenad",
   meet: "Träffa",
   talk: "Prata",
   sit: "Passning",
   crossBreed: "Blandras",
    pureBreed: "Renrasig",
    dontKnow: "Vet inte",
    male: "Hane",
    female: "Hona",
    ownerprofile: "Ägarens profil",
         },
         ddr: {
            name: "Name :",
            sex: " Sex :",
            interest: "Interesse :",
            type: "Type :",
            closestCity: "Nächste Stadt :",
            thereIsNoDataToShowAccordingYourInterest: "Es liegen keine Daten vor, die Ihrem Interesse entsprechen.\n Versuchen Sie, den Abstand zu ändern.",
            alert1: "Internet-Problem",
            title: "Titel",
            like: "MÖGEN",
            nope: "NEE",
            search: "Suche",
            cancel: "Stornieren",
            loading: "Wird geladen",
            home: "Zuhause",
            itsamatchnawww: "Es ist ein Spiel. Nawwww",
   sendmessage: "Nachricht senden",
   continueswipping:"Wischen Sie weiter",
   pleasewat: "Warten Sie mal",
   mate: "Kamerad",
   walk: "Gehen",
   meet: "Treffen",
   talk: "Sich unterhalten",
   sit: "Sitzen",
   crossBreed: "Kreuzung",
    pureBreed: "Reinrassig",
    dontKnow: "Weiß nicht",
    male: "Männlich",
    female: "Weiblich",
    ownerprofile: "Profil des Eigentümers",
         },
         ru: {
            name: "Имя :",
            sex: " Пол :",
            interest: "Интерес :",
            type: "Тип :",
            closestCity: "Ближайший город :",
            thereIsNoDataToShowAccordingYourInterest: "Нет данных для отображения в соответствии с вашими интересами.\n Попробуйте изменить расстояние.",
            alert1: "Проблемы с сетью",
            title: "заглавие",
            like: "НРАВИТСЯ",
            nope: "НЕТ",
            search: "Поиск",
            cancel: "Отменить",
            loading: "Загрузка",

            home: "Главная",
            itsamatchnawww: "Это матч. Nawwww",
   sendmessage: "Отправить сообщение",
   continueswipping:"Продолжить смахивание",
   pleasewat: "подождите пожалуйста",
   mate: "Приятель",
   walk: "Ходить",
   meet: "Встретить",
   talk: "Говорить",
   sit: "Сидеть",
   crossBreed: "Помесь",
    pureBreed: "Чистопородный",
    dontKnow: "Не знаю",
    male: "Он",
    female: "Она",
    ownerprofile: "Профиль владельца",
         }
      });
export default strings
