import SplashLocalization from 'react-native-localization';

let strings = new SplashLocalization({
 "en-US":{
   alert1:"Internet Issue",
   codeMatching:"code matching",
   varified:"Verified",
   sending:"Sending",
   sent:"Sent",
   codesentto: "Code sent to",
   pleaseentervarificationcode: "please enter verification code",
   verify: "Verify",
   resend: "Resend",
   or: "or",
   changephonenumberhere: "Change phone number here",
   cancel: "Change",
   changephonenumber: "changing phone number",
 },
 en:{
  alert1:"Internet Issue",
  codeMatching:"code matching",
  varified:"Verified",
  sending:"Sending",
  sent:"Sent",
  codesentto: "Code sent to",
   pleaseentervarificationcode: "please enter verification code",
   verify: "Verify",
   resend: "Resend",
   or: "or",
   changephonenumberhere: "Change phone number here",
   cancel: "Change",
   changephonenumber: "changing phone number",
 },
 it: {
  alert1:"Problema Internet",
  codeMatching:"Corrispondenza del codice",
  varified:"Verificata",
  sending:"Invio",
  sent:"Inviato",

  codesentto: "Codice inviato a",
   pleaseentervarificationcode: "inserisci il codice di verifica",
   verify: "Verificare",
   resend: "inviare di nuovo",
   or: "o",
   changephonenumberhere: "Cambia il numero di telefono qui",
   cancel: "Modificare",
   changephonenumber: "cambiare il numero di telefono",
 },
 fr:{
  alert1:"Problème Internet",
  codeMatching:"Correspondance de code",
  varified:"Vérifié",
  sending:"Envoi",
  sent:"Envoyé",
  
  codesentto: "Code envoyé à",
   pleaseentervarificationcode: "veuillez entrer le code de vérification",
   verify: "Vérifier",
   resend: "Renvoyer",
   or: "ou",
   changephonenumberhere: "Changer le numéro de téléphone ici",
   cancel: "Changement",
   changephonenumber: "changer de numéro de téléphone",
 },
 es:{
  alert1:"Problema de internet",
  codeMatching:"Coincidencia de código",
  varified:"Verificado",
  sending:"Enviando",
  sent:"Enviado",

  codesentto: "Código enviado a",
   pleaseentervarificationcode: "por favor ingrese el código de verificación",
   verify: "Verificar",
   resend: "Reenviar",
   or: "o",
   changephonenumberhere: "Cambia el número de teléfono aquí",
   cancel: "Cambio",
   changephonenumber: "cambio de numero de telefono",
 },
 sv:{
  alert1:"Nätverksproblem",
  codeMatching:"Kod matchar",
  varified:"Verifierad",
  sending:"Skickar",
  sent:"Skickat",

  codesentto: "Kod skickad till",
   pleaseentervarificationcode: "Vänligen ange verifieringskod",
   verify: "Kontrollera",
   resend: "Skicka igen",
   or: "eller",
   changephonenumberhere: "Ändra telefonnummer här",
   cancel: "Byta",
   changephonenumber: "Byte av telefonnummer",
 },
 ddr:{
  alert1:"Internet-Problem",
  codeMatching:"Code-Übereinstimmung",
  varified:"Verifiziert",
  sending:"Senden",
  sent:"Gesendet",

  codesentto: "Code gesendet an",
   pleaseentervarificationcode: "Bitte geben Sie den Bestätigungscode ein",
   verify: "Überprüfen",
   resend: "Erneut senden",
   or: "oder",
   changephonenumberhere: "Telefonnummer hier ändern",
   cancel: "Veränderung",
   changephonenumber: "Telefonnummer ändern",
 },
 ru:{
  alert1:"Проблемы с сетью",
  codeMatching:"Код совпадает",
  varified:"Проверенный",
  sending:"Отправка",
  sent:"Отправлено",

  codesentto: "Код отправлен",
   pleaseentervarificationcode: "пожалуйста, введите код подтверждения",
   verify: "проверить",
   resend: "Отправить",
   or: "или же",
   changephonenumberhere: "Сменить номер телефона здесь",
   cancel: "+ Изменить",
   changephonenumber: "смена номера телефона",
 }
});
export default strings